@extends('layouts.app')
@section('title', __('technical_failures.create'))
@section('content')
<div class="container-fluid py-3" dir="rtl"><div class="row justify-content-center"><div class="col-xl-9"><div class="d-flex justify-content-between align-items-center mb-4"><h1 class="h4 mb-0">{{ __('technical_failures.create') }}</h1><a href="{{ route('modules.technical-failures.index') }}" class="btn btn-outline-secondary"><i class="bi bi-arrow-right me-1"></i>{{ __('technical_failures.list') }}</a></div>
<form method="post" action="{{ route('modules.technical-failures.store') }}" enctype="multipart/form-data" class="card border-0 shadow-sm"><div class="card-body row g-3">@csrf
<div class="col-md-6"><label class="form-label" for="notice">{{ __('technical_failures.notice') }}</label><input required maxlength="255" class="form-control" id="notice" name="notice" value="{{ old('notice') }}">@error('notice')<div class="text-danger small">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label" for="other">{{ __('technical_failures.other') }}</label><input maxlength="255" class="form-control" id="other" name="other" value="{{ old('other') }}"></div>
@foreach([['section_id','section',$sections],['type_id','type',$types],['platform_id','platform',$platforms],['service_type_id','service_type',$serviceTypes]] as [$field,$label,$items])<div class="col-md-6"><label class="form-label" for="{{ $field }}">{{ __('technical_failures.'.$label) }}</label><select class="form-select" id="{{ $field }}" name="{{ $field }}" {{ in_array($field, ['platform_id','service_type_id'], true) ? 'required' : '' }}><option value="">{{ __('technical_failures.select') }}</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected((string) old($field) === (string) $item->id)>{{ app()->getLocale() === 'ar' ? $item->name_ar : $item->name_en }}</option>@endforeach</select>@error($field)<div class="text-danger small">{{ $message }}</div>@enderror</div>@endforeach
<div class="col-md-6"><label class="form-label" for="attachment">{{ __('technical_failures.attachment') }}</label><input type="file" class="form-control" id="attachment" name="attachment" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"></div></div><div class="card-footer d-flex gap-2"><button class="btn btn-primary" type="submit"><i class="bi bi-check2 me-1"></i>{{ __('technical_failures.save') }}</button><a href="{{ route('modules.technical-failures.index') }}" class="btn btn-light">{{ __('technical_failures.list') }}</a></div></form></div></div></div>
@endsection
