<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><style>body{font-family:DejaVu Sans,sans-serif;font-size:11px}table{width:100%;border-collapse:collapse;margin:12px 0}td,th{border:1px solid #999;padding:5px}h1{font-size:18px}</style></head><body>
<h1>تقرير التنويم رقم 9</h1>
<p>الفترة: {{ $row->period_record->name_ar ?? $row->period_record->name_en ?? $row->period }} — التاريخ: {{ is_numeric($row->date) ? date('Y-m-d',(int)$row->date) : $row->date }} — الموقع: {{ $row->place_record->name_ar ?? $row->place_record->name_en ?? $row->rep_place }}</p>
@if($row->attendance)<p>الحضور: {{ $row->attendance->attendees }} — الغياب: {{ $row->attendance->absence }} — الاستئذان: {{ $row->attendance->permissible }} — المتأخرون: {{ $row->attendance->latecomers }}</p>@endif
<table><thead><tr><th>التاريخ</th><th>رقم الملف</th><th>الموقع</th><th>الغرفة/السرير</th><th>القسم</th><th>الملاحظة</th><th>الإجراء</th><th>أخرى</th></tr></thead><tbody>
@foreach($row->entries as $entry)<tr><td>{{ is_numeric($entry->date ?? null) ? date('Y-m-d',(int)$entry->date) : ($entry->date ?? '') }}</td><td>{{ $entry->filenumber }}</td><td>{{ $entry->location_record->name_ar ?? $entry->location_record->name_en ?? $entry->location }}</td><td>{{ $entry->room_bod_number }}</td><td>{{ $entry->section_record->name_ar ?? $entry->section_record->name_en ?? $entry->section }}</td><td>{{ $entry->notice_record->name_ar ?? $entry->notice_record->name_en ?? $entry->notice }}</td><td>{{ $entry->action_record->name_ar ?? $entry->action_record->name_en ?? $entry->action }}</td><td>{{ $entry->other }}</td></tr>@endforeach
</tbody></table>
<h2 style="font-size:14px">الخدمات المساندة</h2><table><thead><tr><th>التاريخ</th><th>الإدارة</th><th>نوع الخدمة</th><th>نوع الطلب</th><th>الوصف</th></tr></thead><tbody>@foreach($row->support_services as $entry)<tr><td>{{ is_numeric($entry->date ?? null) ? date('Y-m-d',(int)$entry->date) : ($entry->date ?? '') }}</td><td>{{ $entry->maintenance_department_record->name_ar ?? $entry->maintenance_department_record->name_en ?? $entry->maintenance_departments }}</td><td>{{ $entry->maintenance_type_record->name_ar ?? $entry->maintenance_type_record->name_en ?? $entry->maintenance_type }}</td><td>{{ $entry->request_type_record->name_ar ?? $entry->request_type_record->name_en ?? $entry->maintenance_request_type }}</td><td>{{ $entry->description }}</td></tr>@endforeach</tbody></table>
</body></html>
