@extends('layouts.app')
@section('title', __('gov_accounts.notices.new'))
@section('sidebar_heading', __('gov_accounts.title'))
@push('styles')<link href="{{ asset('css/hm-licenses.css') }}?v={{ filemtime(public_path('css/hm-licenses.css')) }}" rel="stylesheet">@endpush
@section('content')<div class="hm-licenses">
@include('licenses.partials.page-header',['title'=>__('gov_accounts.notices.new'),'subtitle'=>__('gov_accounts.notices.subtitle'),'icon'=>'bi-calendar-plus'])
@include('licenses.partials.feedback')
<form method="post" enctype="multipart/form-data" action="{{ $notice ? route('modules.gov-accounts.notices.update',$notice) : route('modules.gov-accounts.notices.store') }}" class="lic-panel"><div class="lic-form-grid">@csrf @if($notice) @method('PUT') @endif
<label class="lic-field lic-field--full"><span>{{ __('gov_accounts.fields.title') }}</span><input name="title" value="{{ old('title',$notice?->title) }}" required></label>
<label class="lic-field"><span>{{ __('gov_accounts.fields.authority') }}</span><select name="authority_id" required><option value="">—</option>@foreach($authorities as $item)<option value="{{ $item->id }}" @selected(old('authority_id',$notice?->authority_id)==$item->id)>{{ $item->localizedName() }}</option>@endforeach</select></label>
<label class="lic-field"><span>{{ __('gov_accounts.fields.service') }}</span><select name="service_id"><option value="">—</option>@foreach($services as $item)<option value="{{ $item->id }}" @selected(old('service_id',$notice?->service_id)==$item->id)>{{ $item->localizedName() }}</option>@endforeach</select></label>
<label class="lic-field lic-field--full"><span>{{ __('gov_accounts.fields.description') }}</span><textarea name="description" required>{{ old('description',$notice?->description) }}</textarea></label>
<label class="lic-field"><span>{{ __('gov_accounts.fields.event_date') }}</span><input type="date" name="event_date" value="{{ old('event_date',$notice?->event_date?->format('Y-m-d')) }}" required></label>
<label class="lic-field"><span>{{ __('gov_accounts.fields.event_time') }}</span><input type="time" name="event_time" value="{{ old('event_time',$notice?->event_time) }}" required></label>
<label class="lic-field"><span>{{ __('gov_accounts.fields.attendance_method') }}</span><select name="attendance_method" required>@foreach(['online','in_person','hybrid'] as $method)<option value="{{ $method }}" @selected(old('attendance_method',$notice?->attendance_method)===$method)>{{ __('gov_accounts.attendance.'.$method) }}</option>@endforeach</select></label>
<label class="lic-field"><span>{{ __('gov_accounts.fields.location') }}</span><input name="location" value="{{ old('location',$notice?->location) }}"></label>
<label class="lic-field lic-field--full"><span>{{ __('gov_accounts.fields.meeting_url') }}</span><input type="url" name="meeting_url" value="{{ old('meeting_url',$notice?->meeting_url) }}"></label>
<label class="lic-field lic-field--full"><span>{{ __('gov_accounts.fields.notes') }}</span><textarea name="notes">{{ old('notes',$notice?->notes) }}</textarea></label>
<label class="lic-field"><span>{{ __('gov_accounts.fields.targeting') }}</span><select name="targeting_mode" required>@foreach(['all','users','departments','service'] as $mode)<option value="{{ $mode }}" @selected(old('targeting_mode',$notice?->targeting['mode']??'all')===$mode)>{{ __('gov_accounts.targeting.'.$mode) }}</option>@endforeach</select></label>
<div class="lic-field lic-field--full"><span>{{ __('gov_accounts.notices.target_users') }}</span><div class="row">@foreach($users as $item)<label class="col-md-4"><input type="checkbox" name="user_ids[]" value="{{ $item->getKey() }}" @checked(in_array($item->getKey(),old('user_ids',$notice?->targeting['mode']==='users' ? $notice->targeting['ids'] : [])))> {{ $item->displayName() }}</label>@endforeach</div><hr><span>{{ __('gov_accounts.notices.target_departments') }}</span><div class="row">@foreach($departments as $item)<label class="col-md-4"><input type="checkbox" name="department_ids[]" value="{{ $item->getKey() }}" @checked(in_array($item->getKey(),old('department_ids',$notice?->targeting['mode']==='departments' ? $notice->targeting['ids'] : [])))> {{ $item->localizedName() }}</label>@endforeach</div><small>{{ __('gov_accounts.notices.target_hint') }}</small></div>
<label class="lic-field lic-field--full"><span>{{ __('gov_accounts.attachments') }}</span><input type="file" name="attachments[]" multiple accept=".pdf,.jpg,.jpeg,.png,.xls,.xlsx"></label>
</div><button class="lic-btn lic-btn--primary" type="submit">{{ __('gov_accounts.actions.save') }}</button></form></div>@endsection
