@extends('layouts.app')
@section('title', $notice->title)
@section('sidebar_heading', __('gov_accounts.title'))
@push('styles')<link href="{{ asset('css/hm-licenses.css') }}?v={{ filemtime(public_path('css/hm-licenses.css')) }}" rel="stylesheet">@endpush
@section('content')<div class="hm-licenses">
@include('licenses.partials.page-header',['title'=>$notice->title,'subtitle'=>__('gov_accounts.notices.subtitle'),'icon'=>'bi-calendar-event'])
@include('licenses.partials.feedback')
<section class="lic-panel"><p>{{ $notice->description }}</p><dl class="row"><dt class="col-sm-3">{{ __('gov_accounts.fields.authority') }}</dt><dd class="col-sm-9">{{ $notice->authority?->localizedName() }}</dd><dt class="col-sm-3">{{ __('gov_accounts.fields.event_date') }}</dt><dd class="col-sm-9">{{ $notice->event_date?->format('Y-m-d') }} {{ $notice->event_time }}</dd><dt class="col-sm-3">{{ __('gov_accounts.fields.attendance_method') }}</dt><dd class="col-sm-9">{{ __('gov_accounts.attendance.'.$notice->attendance_method) }}</dd></dl>
@if(!$notice->sent_at)<a class="lic-btn" href="{{ route('modules.gov-accounts.notices.edit',$notice) }}">{{ __('gov_accounts.actions.edit') }}</a><form method="post" action="{{ route('modules.gov-accounts.notices.send',$notice) }}">@csrf<button class="lic-btn lic-btn--primary" type="submit">{{ __('gov_accounts.notices.send') }}</button></form>@endif</section>
<section class="lic-panel"><h2>{{ __('gov_accounts.attachments') }}</h2><form method="POST" enctype="multipart/form-data" action="{{ route('modules.gov-accounts.notices.attachments.store',$notice) }}">@csrf<input type="file" name="attachment" required accept=".pdf,.jpg,.jpeg,.png,.xls,.xlsx"><button class="lic-btn" type="submit">{{ __('gov_accounts.actions.upload') }}</button></form>@forelse($notice->attachments as $attachment)<a class="d-block py-1" href="{{ route('modules.gov-accounts.notices.attachments.download',[$notice,$attachment]) }}">{{ $attachment->original_name }}</a>@empty<p class="lic-empty">{{ __('gov_accounts.admin.empty') }}</p>@endforelse</section>
<section class="lic-panel"><h2>{{ __('gov_accounts.notices.recipients') }}</h2><div class="lic-table-wrap"><table class="lic-table"><thead><tr><th>{{ __('gov_accounts.fields.employee') }}</th><th>{{ __('gov_accounts.fields.email') }}</th><th>{{ __('gov_accounts.fields.status') }}</th><th>{{ __('gov_accounts.fields.viewed_at') }}</th></tr></thead><tbody>@forelse($notice->recipients as $recipient)<tr><td>{{ $recipient->user?->displayName() }}</td><td>{{ $recipient->email }}</td><td>{{ $recipient->viewed_at ? __('gov_accounts.notices.viewed') : ($recipient->sent_at ? __('gov_accounts.notices.not_viewed') : __('gov_accounts.notices.sent')) }}</td><td>{{ $recipient->viewed_at?->format('Y-m-d H:i') }}</td></tr>@empty<tr><td colspan="4" class="lic-empty">{{ __('gov_accounts.notices.no_recipients') }}</td></tr>@endforelse</tbody></table></div></section>
</div>@endsection
