@extends('layouts.app')
@section('title','استفسار الإجازات')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h4 mb-1">استفسار الإجازات</h1><p class="text-muted mb-0">طلبات الإجازات الطبية وقرارات الإدارة</p></div><button class="btn btn-primary" data-bs-toggle="collapse" data-bs-target="#holiday-create">إضافة استفسار</button></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="collapse mb-4" id="holiday-create"><form method="post" enctype="multipart/form-data" action="{{ route('modules.legacy-office.holidays.store') }}" class="card card-body border-0 shadow-sm">@csrf
<div class="row g-3"><div class="col-md-4"><label class="form-label">اسم المريض</label><input required class="form-control" name="patient_name"></div><div class="col-md-2"><label class="form-label">الجنسية</label><input required class="form-control" name="nationality"></div><div class="col-md-3"><label class="form-label">رقم الهوية</label><input required class="form-control" name="idno" maxlength="12"></div><div class="col-md-3"><label class="form-label">رقم الملف</label><input required class="form-control" name="file_number"></div><div class="col-md-2"><label class="form-label">عدد الأيام</label><input required min="1" type="number" class="form-control" name="days"></div><div class="col-md-3"><label class="form-label">تاريخ الإصدار</label><input required type="date" class="form-control" name="issue_date"></div><div class="col-md-4"><label class="form-label">جهة الإصدار</label><input required class="form-control" name="issuer"></div><div class="col-md-2"><label class="form-label">النوع</label><input required min="1" type="number" class="form-control" name="type" value="1"></div><div class="col-md-4"><label class="form-label">المرفق</label><input type="file" class="form-control" name="attachment" accept=".jpg,.jpeg,.png,.gif,.pdf,.docx"></div><div class="col-12"><button class="btn btn-primary">حفظ</button></div></div></form></div>
@include('legacy-office.partials.filters',['filterDecisions'=>$decisions])
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>التاريخ</th><th>اسم المريض</th><th>رقم الهوية</th><th>رقم الملف</th><th>الأيام</th><th>المدخل</th><th>مدير العيادات</th><th>الخط الزمني</th><th>الإجراء</th></tr></thead><tbody>@forelse($records as $record)<tr><td>{{ is_numeric($record->created_at)?date('Y-m-d H:i',(int)$record->created_at):$record->created_at }}</td><td>{{ $record->patient_name }}</td><td>{{ $record->idno }}</td><td>{{ $record->file_number }}</td><td>{{ $record->days }}</td><td>{{ $userNames[$record->user_id] ?? '#'.$record->user_id }}</td><td>@if($record->manager_reply==1)<span class="badge bg-success">تمت الموافقة</span>@elseif($record->manager_reply==2)<span class="badge bg-danger" title="{{ $record->manager_reply_reason }}">مرفوض</span>@else<span class="badge bg-warning text-dark">معلق</span>@endif @if($record->manager)<small>{{$userNames[$record->manager] ?? '#'.$record->manager}}</small>@endif</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('modules.legacy-office.holidays.timeline',$record->id) }}">التفاصيل</a></td><td class="text-nowrap"><a class="btn btn-sm btn-outline-secondary" target="_blank" href="{{ route('modules.legacy-office.holidays.pdf',$record->id) }}">PDF</a> @if($canDecide)<button class="btn btn-sm btn-dark" data-bs-toggle="modal" data-bs-target="#decision-{{ $record->id }}">قرار</button>@endif</td></tr>
<div class="modal fade" id="decision-{{ $record->id }}" tabindex="-1"><div class="modal-dialog"><form method="post" action="{{ route('modules.legacy-office.holidays.decision',$record->id) }}" class="modal-content">@csrf @method('patch')<div class="modal-header"><h2 class="h5 modal-title">إضافة القرار</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><select required class="form-select mb-3" name="manager_reply">@foreach($decisions as $decision)<option value="{{ $decision->id }}">{{ $decision->name_ar }}</option>@endforeach</select><input class="form-control" name="manager_reply_reason" placeholder="كتابة السبب"></div><div class="modal-footer"><button class="btn btn-primary">حفظ</button></div></form></div></div>
@empty<tr><td colspan="9" class="text-center text-muted py-5">لا توجد نتائج</td></tr>@endforelse</tbody></table></div><div class="card-footer bg-transparent">{{ $records->links() }}</div></div>
@endsection
