@extends('layouts.app')
@section('title',$received?'المذكرات الواردة':'المذكرات')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h4 mb-1">{{$received?'المذكرات الواردة':'المذكرات'}}</h1><p class="text-muted mb-0">{{$received?'المذكرات المرسلة إليك وحالة الاطلاع':'إنشاء واعتماد وإرسال المذكرات للموظفين'}}</p></div>@unless($received)<button class="btn btn-primary" data-bs-toggle="collapse" data-bs-target="#memo-create">إضافة مذكرة</button>@endunless</div>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif @if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif
@unless($received)<div class="collapse mb-4" id="memo-create"><form method="post" action="{{route('modules.legacy-office.memos.store')}}" class="card card-body border-0 shadow-sm">@csrf @include('legacy-office.partials.memo-form',['record'=>null])<button class="btn btn-primary mt-3">حفظ وإرسال</button></form></div>@endunless
@include('legacy-office.partials.filters',['filterTypes'=>$types])
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>تاريخ الإصدار</th><th>نوع المذكرة</th><th>أرسل إلى</th><th>اعتماد المذكرة</th><th>PDF</th></tr></thead><tbody>@forelse($records as $record)<tr><td>{{is_numeric($record->date)?date('Y-m-d H:i',(int)$record->date):$record->date}}</td><td>{{$record->type_name}}</td><td><span class="badge bg-secondary">{{$record->recipient_count}}</span></td><td>{{$record->activated_at?$record->activated_at:'غير معتمد'}} @unless($received)<button class="btn btn-sm btn-dark" data-bs-toggle="modal" data-bs-target="#memo-{{$record->id}}">تعديل واعتماد</button>@endunless</td><td><a target="_blank" class="btn btn-sm btn-outline-secondary" href="{{route('modules.legacy-office.memos.pdf',$record->id)}}">PDF</a></td></tr>
@unless($received)<div class="modal fade" id="memo-{{$record->id}}" tabindex="-1"><div class="modal-dialog modal-lg"><form method="post" action="{{route('modules.legacy-office.memos.update',$record->id)}}" class="modal-content">@csrf @method('put')<div class="modal-header"><h2 class="h5">اعتماد المذكرة #{{$record->id}}</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('legacy-office.partials.memo-form',['record'=>$record])</div><div class="modal-footer"><button class="btn btn-primary">اعتماد</button></div></form></div></div>@endunless
@empty<tr><td colspan="5" class="text-center text-muted py-5">لا توجد نتائج</td></tr>@endforelse</tbody></table></div><div class="card-footer bg-transparent">{{$records->links()}}</div></div>
@endsection
