<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->getLocale()==='ar'?'rtl':'ltr' }}">
<head><meta charset="utf-8"><title>{{ __('licenses.pdf.record_title') }}</title><style>
@page{margin:20mm 14mm}body{font-family:DejaVu Sans,sans-serif;color:#203449;font-size:11px;line-height:1.6}h1{margin:0;color:#18334f;font-size:20px}h2{margin:18px 0 7px;color:#18334f;font-size:14px;border-bottom:2px solid #1f5f96;padding-bottom:4px}.head{display:table;width:100%;border-bottom:3px solid #1f5f96;padding-bottom:12px}.head>div{display:table-cell;vertical-align:middle}.meta{text-align:end;color:#687989}.badge{display:inline-block;padding:3px 8px;border-radius:10px;background:#eaf4fc;color:#1f5f96;font-weight:bold}table{width:100%;border-collapse:collapse;margin-top:7px}th,td{border:1px solid #ccd9e3;padding:6px;vertical-align:top}th{background:#f1f6f9;color:#334b61;text-align:start;width:20%}.list th{width:auto}.muted{color:#687989}.footer{margin-top:25px;padding-top:7px;border-top:1px solid #ccd9e3;color:#687989;text-align:center;font-size:9px}.ltr{direction:ltr;text-align:start}
</style></head><body>
@php
$nameOf=static function($i){if(!$i)return '—';if(is_string($i))return $i;if(method_exists($i,'displayName'))return $i->displayName();if(method_exists($i,'localizedName'))return $i->localizedName();$f=app()->getLocale()==='ar'?'name_ar':'name_en';return data_get($i,$f)?:data_get($i,'name')?:data_get($i,'hr_name')?:'—';};
$dateOf=static fn($v,$time=false)=>$v?($v instanceof \DateTimeInterface?$v->format($time?'Y-m-d H:i':'Y-m-d'):substr((string)$v,0,$time?16:10)):'—';
$timelineNotice=static function($notice){if(!is_string($notice)||!str_starts_with($notice,'licenses.timeline.'))return $notice;$key=substr($notice,strlen('licenses.timeline.'));$eventKey='licenses.timeline.events.'.$key;$event=__($eventKey);if($event!==$eventKey)return $event;$rootKey='licenses.timeline.'.$key;$root=__($rootKey);return $root!==$rootKey?$root:$notice;};
$isListReport=(bool)($isListReport ?? false);$items=collect($licenses ?? []);
@endphp
@if($isListReport)
<header class="head"><div><h1>{{ __('licenses.pdf.list_title') }}</h1><span class="muted">{{ __('licenses.results',['count'=>$items->count()]) }}</span></div><div class="meta"><strong>{{ __('licenses.pdf.generated_at') }}</strong><br>{{ $dateOf($generatedAt ?? now(),true) }}</div></header>
<table class="list"><thead><tr><th>{{ __('licenses.fields.license_number') }}</th><th>{{ __('licenses.fields.title') }}</th><th>{{ __('licenses.fields.authority') }}</th><th>{{ __('licenses.fields.type') }}</th><th>{{ __('licenses.fields.branches') }}</th><th>{{ __('licenses.fields.responsible') }}</th><th>{{ __('licenses.fields.expiry_date') }}</th><th>{{ __('licenses.fields.status') }}</th><th>{{ __('licenses.fields.renewal_stage') }}</th></tr></thead><tbody>
@forelse($items as $item)<tr><td>{{ $item->license_number ?: '#'.$item->id }}</td><td>{{ $item->title ?: $nameOf($item->type ?? null) }}</td><td>{{ $nameOf($item->authority ?? null) }}</td><td>{{ $nameOf($item->type ?? null) }}</td><td>{{ ($item->branches ?? collect())->map(fn($b)=>$nameOf($b))->implode('، ') ?: '—' }}</td><td>{{ $nameOf($item->responsibleUser ?? null) }}</td><td class="ltr">{{ $dateOf($item->expiry_date) }}</td><td>{{ $nameOf($item->status ?? null) }}</td><td>{{ $nameOf($item->renewalStage ?? null) }}</td></tr>@empty<tr><td colspan="9">—</td></tr>@endforelse
</tbody></table>
<footer class="footer">{{ __('licenses.pdf.confidential') }} · {{ __('licenses.pdf.generated_at') }}: {{ $dateOf($generatedAt ?? now(),true) }}</footer>
@else
@php
$status=$license->statusRelation ?? $license->status ?? null;$timeline=$timelineEntries ?? $license->timelineEntries ?? $license->timeline ?? collect();$renewals=$renewalHistory ?? $license->renewals ?? collect();$attachments=$license->attachments ?? collect();$payments=$license->paymentRequests ?? collect();
@endphp
<header class="head"><div><h1>{{ __('licenses.pdf.record_title') }}</h1><span class="muted">{{ $license->title ?: $nameOf($license->licenseType ?? $license->type ?? null) }}</span></div><div class="meta"><strong>{{ $license->license_number ?: '#'.$license->id }}</strong><br><span class="badge">{{ $nameOf($status) }}</span></div></header>
<h2>{{ __('licenses.sections.summary') }}</h2><table>
<tr><th>{{ __('licenses.fields.authority') }}</th><td>{{ $nameOf($license->authority ?? null) }}</td><th>{{ __('licenses.fields.type') }}</th><td>{{ $nameOf($license->licenseType ?? $license->type ?? null) }}</td></tr>
<tr><th>{{ __('licenses.fields.responsible') }}</th><td>{{ $nameOf($license->responsibleUser ?? $license->responsible ?? null) }}</td><th>{{ __('licenses.fields.branches') }}</th><td>{{ ($license->branches ?? collect())->map(fn($b)=>$nameOf($b))->implode('، ') ?: '—' }}</td></tr>
<tr><th>{{ __('licenses.fields.issue_date') }}</th><td class="ltr">{{ $dateOf($license->issue_date) }}</td><th>{{ __('licenses.fields.expiry_date') }}</th><td class="ltr">{{ $dateOf($license->expiry_date) }}</td></tr>
<tr><th>{{ __('licenses.fields.renewal_stage') }}</th><td>{{ $nameOf($license->renewalStage ?? $license->stage ?? null) }}</td><th>{{ __('licenses.fields.updated_at') }}</th><td class="ltr">{{ $dateOf($license->updated_at,true) }}</td></tr>
<tr><th>{{ __('licenses.fields.notes') }}</th><td colspan="3">{{ $license->notes ?: '—' }}</td></tr></table>
<h2>{{ __('licenses.sections.history') }}</h2><table class="list"><thead><tr><th>{{ __('licenses.renewal.previous_expiry') }}</th><th>{{ __('licenses.renewal.new_expiry') }}</th><th>{{ __('licenses.renewal.started_at') }}</th><th>{{ __('licenses.renewal.completed_at') }}</th></tr></thead><tbody>@forelse($renewals->sortByDesc('id') as $renewal)<tr><td>{{ $dateOf($renewal->previous_expiry_date) }}</td><td>{{ $dateOf($renewal->new_expiry_date) }}</td><td>{{ $dateOf($renewal->started_at,true) }}</td><td>{{ $dateOf($renewal->completed_at,true) }}</td></tr>@empty<tr><td colspan="4">—</td></tr>@endforelse</tbody></table>
<h2>{{ __('licenses.sections.payments') }}</h2><table class="list"><thead><tr><th>{{ __('licenses.payments.request_number') }}</th><th>{{ __('licenses.payments.amount') }}</th><th>{{ __('licenses.payments.status') }}</th><th>{{ __('licenses.payments.requested_at') }}</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>#{{ $payment->id }}</td><td>{{ number_format((float)$payment->amount,2) }} {{ $payment->currency?:'SAR' }}</td><td>{{ $nameOf($payment->statusRelation ?? $payment->status ?? null) }}</td><td>{{ $dateOf($payment->created_at,true) }}</td></tr>@empty<tr><td colspan="4">—</td></tr>@endforelse</tbody></table>
<h2>{{ __('licenses.sections.attachments') }}</h2><table class="list"><thead><tr><th>{{ __('licenses.attachments.file') }}</th><th>{{ __('licenses.attachments.context') }}</th><th>{{ __('licenses.attachments.uploaded_at') }}</th></tr></thead><tbody>@forelse($attachments as $attachment)<tr><td>{{ $attachment->original_name }}</td><td>{{ __('licenses.attachments.contexts.'.($attachment->context?:'license')) }}</td><td>{{ $dateOf($attachment->uploaded_at ?? $attachment->created_at,true) }}</td></tr>@empty<tr><td colspan="3">—</td></tr>@endforelse</tbody></table>
<h2>{{ __('licenses.sections.timeline') }}</h2><table class="list"><thead><tr><th>{{ __('licenses.notifications.event') }}</th><th>{{ __('licenses.fields.description') }}</th><th>{{ __('licenses.fields.created_at') }}</th></tr></thead><tbody>@forelse($timeline->sortByDesc('id') as $entry)<tr><td>{{ __('licenses.timeline.events.'.($entry->event_type?:'settings_changed')) }}</td><td>{{ $timelineNotice($entry->notice)?:'—' }}</td><td>{{ $dateOf($entry->date ?? $entry->created_at,true) }}</td></tr>@empty<tr><td colspan="3">—</td></tr>@endforelse</tbody></table>
<footer class="footer">{{ __('licenses.pdf.confidential') }} · {{ __('licenses.pdf.generated_at') }}: {{ $dateOf($generatedAt ?? now(),true) }} @if(!empty($generatedBy)) · {{ __('licenses.pdf.generated_by') }}: {{ $nameOf($generatedBy) }} @endif</footer>
@endif
</body></html>
