@extends('layouts.app')
@section('title', __('gov_accounts.requests.new'))
@section('sidebar_heading', __('gov_accounts.title'))
@push('styles')<link href="{{ asset('css/hm-licenses.css') }}?v={{ filemtime(public_path('css/hm-licenses.css')) }}" rel="stylesheet">@endpush
@section('content')@php($editing=(bool)$accountRequest)<div class="hm-licenses">
@include('licenses.partials.page-header',['title'=>$editing?__('gov_accounts.actions.edit'):__('gov_accounts.requests.new'),'subtitle'=>__('gov_accounts.requests.subtitle'),'icon'=>'bi-file-earmark-plus'])
<section class="lic-panel"><form method="POST" action="{{ $editing?route('modules.gov-accounts.requests.update',$accountRequest):route('modules.gov-accounts.requests.store') }}">@csrf @if($editing)@method('PUT')@endif<div class="lic-form-grid">
@foreach([['employee_user_id',__('gov_accounts.fields.employee'),$employees,'displayName'],['department_id',__('gov_accounts.fields.department'),$departments,'localizedName'],['authority_id',__('gov_accounts.fields.authority'),$authorities,'localizedName'],['service_id',__('gov_accounts.fields.service'),$services,'localizedName'],['role_id',__('gov_accounts.fields.role'),$roles,'localizedName']] as [$name,$label,$options,$method])<div class="lic-field"><label for="{{ $name }}">{{ $label }}</label><select class="form-select" id="{{ $name }}" name="{{ $name }}" required><option value="">—</option>@foreach($options as $option)<option value="{{ $option->getKey() }}" @selected((int)old($name,$accountRequest?->{$name})===(int)$option->getKey())>{{ $option->{$method}() }}</option>@endforeach</select>@error($name)<div class="text-danger">{{ $message }}</div>@enderror</div>@endforeach
<div class="lic-field lic-field--span-2"><label for="justification">{{ __('gov_accounts.fields.justification') }}</label><textarea class="form-control" id="justification" name="justification" rows="4" required>{{ old('justification',$accountRequest?->justification) }}</textarea>@error('justification')<div class="text-danger">{{ $message }}</div>@enderror</div>
<div class="lic-field lic-field--span-2"><label for="notes">{{ __('gov_accounts.fields.notes') }}</label><textarea class="form-control" id="notes" name="notes" rows="3">{{ old('notes',$accountRequest?->notes) }}</textarea></div></div>
<div class="lic-form-actions"><button class="lic-btn lic-btn--primary">{{ __('gov_accounts.actions.save') }}</button><a class="lic-btn" href="{{ route('modules.gov-accounts.requests.index') }}">{{ __('gov_accounts.actions.cancel') }}</a></div></form></section></div>@endsection
