@extends('layouts.app')
@section('title', __('gov_accounts.requests.number',['id'=>$accountRequest->id]))
@section('sidebar_heading', __('gov_accounts.title'))
@push('styles')<link href="{{ asset('css/hm-licenses.css') }}?v={{ filemtime(public_path('css/hm-licenses.css')) }}" rel="stylesheet">@endpush
@section('content')
<div class="hm-licenses">
@include('licenses.partials.page-header',['title'=>__('gov_accounts.requests.number',['id'=>$accountRequest->id]),'subtitle'=>__('gov_accounts.statuses.'.$accountRequest->status),'icon'=>'bi-file-earmark-person','actions'=>new \Illuminate\Support\HtmlString('<a class="lic-btn" href="'.e(route('modules.gov-accounts.requests.index')).'">'.e(__('gov_accounts.actions.back')).'</a>')])
@include('licenses.partials.feedback')
<section class="lic-panel"><div class="lic-detail-grid"><div><small>{{ __('gov_accounts.fields.employee') }}</small><strong>{{ $accountRequest->employee?->displayName() }}</strong></div><div><small>{{ __('gov_accounts.fields.department') }}</small><strong>{{ $accountRequest->department?->localizedName() }}</strong></div><div><small>{{ __('gov_accounts.fields.authority') }}</small><strong>{{ $accountRequest->authority?->localizedName() }}</strong></div><div><small>{{ __('gov_accounts.fields.service') }}</small><strong>{{ $accountRequest->service?->localizedName() }}</strong></div><div><small>{{ __('gov_accounts.fields.role') }}</small><strong>{{ $accountRequest->role?->localizedName() }}</strong></div><div><small>{{ __('gov_accounts.fields.round') }}</small><strong>{{ $accountRequest->round }}</strong></div></div><p>{{ $accountRequest->justification }}</p>@if($accountRequest->rejection_reason)<div class="alert alert-danger">{{ $accountRequest->rejection_reason }}</div>@endif</section>
@if(($abilities['head']??false) && in_array($accountRequest->status,['draft','rejected']))<section class="lic-panel"><a class="lic-btn" href="{{ route('modules.gov-accounts.requests.edit',$accountRequest) }}">{{ __('gov_accounts.actions.edit') }}</a>@if($accountRequest->status==='draft')<form method="POST" action="{{ route('modules.gov-accounts.requests.submit',$accountRequest) }}">@csrf<label class="lic-checkbox"><input type="checkbox" name="manager_undertaking" value="1" required><span>{{ __('gov_accounts.undertakings.manager_text') }}</span></label><button class="lic-btn lic-btn--primary">{{ __('gov_accounts.actions.submit') }}</button></form>@else<form method="POST" action="{{ route('modules.gov-accounts.requests.resubmit',$accountRequest) }}">@csrf<textarea name="response" class="form-control" required placeholder="{{ __('gov_accounts.fields.response') }}"></textarea><button class="lic-btn lic-btn--primary">{{ __('gov_accounts.actions.resubmit') }}</button></form>@endif</section>@endif
@if(($abilities['processor']??false) && $accountRequest->status==='under_review')<section class="lic-panel"><form method="POST" action="{{ route('modules.gov-accounts.requests.approve',$accountRequest) }}">@csrf<textarea name="notes" class="form-control" placeholder="{{ __('gov_accounts.fields.notes') }}"></textarea><button class="lic-btn lic-btn--primary">{{ __('gov_accounts.actions.approve') }}</button></form><form method="POST" action="{{ route('modules.gov-accounts.requests.reject',$accountRequest) }}">@csrf<textarea name="reason" class="form-control" required placeholder="{{ __('gov_accounts.fields.rejection_reason') }}"></textarea><button class="lic-btn">{{ __('gov_accounts.actions.reject') }}</button></form></section>@endif
@if(($abilities['processor']??false) && $accountRequest->status==='approved')<section class="lic-panel"><form method="POST" action="{{ route('modules.gov-accounts.requests.authority',$accountRequest) }}">@csrf<input type="date" name="authority_submitted_at" value="{{ now()->toDateString() }}" required class="form-control"><input name="authority_reference" class="form-control" placeholder="{{ __('gov_accounts.fields.reference_no') }}"><textarea name="notes" class="form-control" placeholder="{{ __('gov_accounts.fields.notes') }}"></textarea><button class="lic-btn lic-btn--primary">{{ __('gov_accounts.actions.mark_authority') }}</button></form></section>@endif
@if(($abilities['processor']??false) && $accountRequest->status==='submitted_to_authority')<section class="lic-panel"><form method="POST" action="{{ route('modules.gov-accounts.requests.complete',$accountRequest) }}">@csrf @if($accountRequest->type==='create')<div class="lic-form-grid"><input name="username" class="form-control" required placeholder="{{ __('gov_accounts.fields.username') }}"><input name="login_url" type="url" class="form-control" placeholder="{{ __('gov_accounts.fields.login_url') }}"><input name="reference_no" class="form-control" placeholder="{{ __('gov_accounts.fields.reference_no') }}"><select name="role_id" class="form-select" required>@foreach($roles as $role)<option value="{{ $role->id }}" @selected($role->id===$accountRequest->role_id)>{{ $role->localizedName() }}</option>@endforeach</select><input type="date" name="account_created_at" value="{{ now()->toDateString() }}" required class="form-control"></div>@else<p>{{ __('gov_accounts.lifecycle.confirm_complete') }}</p>@endif<button class="lic-btn lic-btn--primary">{{ __('gov_accounts.actions.complete') }}</button></form></section>@endif
<section class="lic-panel"><h3>{{ __('gov_accounts.attachments') }}</h3>@if($abilities['attach']??false)<form method="POST" enctype="multipart/form-data" action="{{ route('modules.gov-accounts.requests.attachments.store',$accountRequest) }}">@csrf<input type="hidden" name="context" value="request"><input type="file" name="attachment" required accept=".pdf,.jpg,.jpeg,.png,.xls,.xlsx"><button class="lic-btn">{{ __('gov_accounts.actions.upload') }}</button></form>@endif @foreach($accountRequest->attachments as $attachment)<a href="{{ route('modules.gov-accounts.requests.attachments.download',[$accountRequest,$attachment]) }}">{{ $attachment->original_name }}</a>@endforeach</section>
<section class="lic-panel"><h3>{{ __('gov_accounts.timeline.title') }}</h3>@foreach($accountRequest->timeline as $event)<div class="border-bottom py-2"><strong>{{ __('gov_accounts.timeline.events.'.$event->event_type) }}</strong><small>{{ $event->date?->format('Y-m-d H:i') }}</small><p>{{ $event->notice }}</p></div>@endforeach</section>
</div>
@endsection
