@extends('layouts.app')

@section('title', __('emergency_follow_up.print'))

@push('styles')<style>@media print{.hm-hope-banner,.sidebar,.main-sidebar,.hm-app-sidebar,.hm-footer,.hm-print-actions{display:none!important}.main-content{margin:0!important}.content-inner{padding:0!important}.card{box-shadow:none!important;border:1px solid #999!important}}</style>@endpush

@section('content')
    <div class="d-flex justify-content-between align-items-center mb-3 hm-print-actions"><h1 class="h4 mb-0">{{ __('emergency_follow_up.print') }}</h1><button class="btn btn-primary" type="button" onclick="window.print()"><i class="bi bi-printer me-1" aria-hidden="true"></i>{{ __('emergency_follow_up.print') }}</button></div>
    <div class="card border-0 shadow-sm"><div class="card-body"><h1 class="h5 text-center mb-4">{{ __('emergency_follow_up.detail') }} #{{ $followUp->id }}</h1><table class="table table-bordered"><tbody><tr><th>{{ __('emergency_follow_up.date') }}</th><td dir="ltr">{{ date('Y-m-d H:i', (int) $followUp->date) }}</td><th>{{ __('emergency_follow_up.file_number') }}</th><td>{{ $followUp->file_number }}</td></tr><tr><th>{{ __('emergency_follow_up.notice') }}</th><td>{{ app()->getLocale() === 'ar' ? $followUp->noticeType?->name_ar : $followUp->noticeType?->name_en }}</td><th>{{ __('emergency_follow_up.status') }}</th><td>{{ (int) $followUp->status === 1 ? __('emergency_follow_up.closed_status') : __('emergency_follow_up.open_status') }}</td></tr><tr><th>{{ __('emergency_follow_up.description') }}</th><td colspan="3">{{ $followUp->description }}</td></tr><tr><th>{{ __('emergency_follow_up.action') }}</th><td colspan="3">{{ $followUp->action }}</td></tr></tbody></table><h2 class="h6 mt-4">{{ __('emergency_follow_up.notice_history') }}</h2><table class="table table-bordered"><thead><tr><th>{{ __('emergency_follow_up.notice') }}</th><th>{{ __('emergency_follow_up.created_at') }}</th><th>{{ __('emergency_follow_up.created_by') }}</th></tr></thead><tbody>@forelse($followUp->notices as $notice)<tr><td>{{ $notice->notice }}</td><td dir="ltr">{{ $notice->created_at }}</td><td>{{ $notice->creator?->displayName() ?: '—' }}</td></tr>@empty<tr><td colspan="3">{{ __('emergency_follow_up.no_notices') }}</td></tr>@endforelse</tbody></table></div></div>
@endsection
