@extends('layouts.app')

@section('title', __('emergency_follow_up.detail'))

@section('content')
    <div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><h1 class="h4 mb-1">{{ __('emergency_follow_up.detail') }} #{{ $followUp->id }}</h1><p class="text-muted mb-0">{{ __('emergency_follow_up.subtitle') }}</p></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="{{ route('modules.emergency-follow-up.print', $followUp->id) }}"><i class="bi bi-printer me-1" aria-hidden="true"></i>{{ __('emergency_follow_up.print') }}</a><a class="btn btn-light" href="{{ route('modules.emergency-follow-up.index') }}">{{ __('emergency_follow_up.back') }}</a></div></div>
    @if (session('success'))<div class="alert alert-success" role="status">{{ session('success') }}</div>@endif
    <div class="row g-3"><div class="col-xl-7"><div class="card border-0 shadow-sm"><div class="card-body"><dl class="row mb-0"><dt class="col-sm-4">{{ __('emergency_follow_up.date') }}</dt><dd class="col-sm-8" dir="ltr">{{ date('Y-m-d H:i', (int) $followUp->date) }}</dd><dt class="col-sm-4">{{ __('emergency_follow_up.file_number') }}</dt><dd class="col-sm-8">{{ $followUp->file_number }}</dd><dt class="col-sm-4">{{ __('emergency_follow_up.notice') }}</dt><dd class="col-sm-8">{{ app()->getLocale() === 'ar' ? $followUp->noticeType?->name_ar : $followUp->noticeType?->name_en }}</dd><dt class="col-sm-4">{{ __('emergency_follow_up.notice_type') }}</dt><dd class="col-sm-8">{{ (int) $followUp->notice_type === 1 ? __('emergency_follow_up.urgent') : __('emergency_follow_up.non_urgent') }}</dd><dt class="col-sm-4">{{ __('emergency_follow_up.status') }}</dt><dd class="col-sm-8">{{ (int) $followUp->status === 1 ? __('emergency_follow_up.closed_status') : __('emergency_follow_up.open_status') }}</dd><dt class="col-sm-4">{{ __('emergency_follow_up.description') }}</dt><dd class="col-sm-8">{{ $followUp->description }}</dd><dt class="col-sm-4">{{ __('emergency_follow_up.action') }}</dt><dd class="col-sm-8">{{ $followUp->action }}</dd><dt class="col-sm-4">{{ __('emergency_follow_up.created_by') }}</dt><dd class="col-sm-8">{{ $followUp->creator?->displayName() ?: '—' }}</dd></dl></div></div></div>
        <div class="col-xl-5"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h6">{{ __('emergency_follow_up.add_notice') }}</h2><form method="post" action="{{ route('modules.emergency-follow-up.notices.store', $followUp->id) }}">@csrf<textarea class="form-control @error('notice') is-invalid @enderror" name="notice" rows="4" required maxlength="5000">{{ old('notice') }}</textarea>@error('notice')<div class="invalid-feedback">{{ $message }}</div>@enderror<button class="btn btn-primary mt-3" type="submit"><i class="bi bi-plus-lg me-1" aria-hidden="true"></i>{{ __('emergency_follow_up.save_notice') }}</button></form>@if ((int) $followUp->status === 2)<form class="mt-3" method="post" action="{{ route('modules.emergency-follow-up.close', $followUp->id) }}">@csrf<button class="btn btn-outline-danger" type="submit"><i class="bi bi-check2-circle me-1" aria-hidden="true"></i>{{ __('emergency_follow_up.close') }}</button></form>@endif</div></div></div></div>
    <div class="card border-0 shadow-sm mt-3"><div class="card-body"><h2 class="h6">{{ __('emergency_follow_up.notice_history') }}</h2><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>{{ __('emergency_follow_up.notice') }}</th><th>{{ __('emergency_follow_up.created_at') }}</th><th>{{ __('emergency_follow_up.created_by') }}</th></tr></thead><tbody>@forelse ($followUp->notices as $notice)<tr><td>{{ $notice->notice }}</td><td dir="ltr">{{ $notice->created_at }}</td><td>{{ $notice->creator?->displayName() ?: '—' }}</td></tr>@empty<tr><td colspan="3" class="text-muted">{{ __('emergency_follow_up.no_notices') }}</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
