@extends('layouts.app')
@section('title', 'نموذج الهوية الوطنية وشراء الخدمة الصحية')
@section('content')
<h1 class="h4 mb-4">نموذج الهوية الوطنية وشراء الخدمة الصحية</h1>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}@if(session('public_url'))<div class="mt-2"><a href="{{ session('public_url') }}" target="_blank">{{ session('public_url') }}</a></div>@endif</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card border-0 shadow-sm mb-3"><div class="card-header"><strong>إرسال نموذج جديد</strong></div><form method="post" action="{{ route('modules.health-service-purchase.store') }}"><div class="card-body row g-3 align-items-end">@csrf<div class="col-md-4"><label class="form-label">نوع الهوية</label><select class="form-select" name="id_type" required><option value="1">هوية وطنية</option><option value="2">إقامة</option></select></div><div class="col-md-4"><label class="form-label">رقم الجوال</label><input class="form-control" name="mobile" required pattern="05[0-9]{8}" maxlength="10"></div><div class="col-md-4"><button class="btn btn-primary">إنشاء رابط النموذج</button></div></div></form></div>
<form class="card border-0 shadow-sm mb-3" method="get"><div class="card-body row g-3 align-items-end"><div class="col-md-2"><label class="form-label">من تاريخ</label><input class="form-control" type="date" name="from" value="{{ $filters['from'] }}"></div><div class="col-md-2"><label class="form-label">إلى تاريخ</label><input class="form-control" type="date" name="to" value="{{ $filters['to'] }}"></div><div class="col-md-2"><label class="form-label">الحالة</label><select class="form-select" name="status"><option value="">الكل</option><option value="0" @selected($filters['status']==='0')>معلق</option><option value="1" @selected($filters['status']==='1')>صحيح</option><option value="2" @selected($filters['status']==='2')>غير صحيح</option></select></div><div class="col-md-4"><label class="form-label">رقم الهوية</label><input class="form-control" name="search" value="{{ $filters['search'] }}"></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">بحث</button></div></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>تاريخ الإصدار</th><th>نوع النموذج</th><th>الاسم</th><th>رقم الهوية</th><th>مدخل البيانات</th><th>التحقق</th><th>المرفقات والإجراءات</th></tr></thead><tbody>@forelse($records as $record)<tr><td>{{ date('Y-m-d',(int)$record->date) }}</td><td>{{ $record->id_type==1?'هوية وطنية':'إقامة' }}</td><td>{{ $record->name ?: 'لم تتم التعبئة' }}</td><td>{{ $record->id_number ?: '—' }}</td><td>{{ $record->hr_first_name }} {{ $record->hr_last_name }}</td><td>@if(!$record->verified)<form method="post" action="{{ route('modules.health-service-purchase.status',$record->id) }}" class="d-flex gap-1">@csrf<select class="form-select form-select-sm" name="verified"><option value="1">صحيح</option><option value="2">غير صحيح</option></select><button class="btn btn-sm btn-primary">حفظ</button></form>@elseif($record->verified==1)<span class="badge bg-success">صحيح</span>@else<span class="badge bg-danger">غير صحيح</span>@endif</td><td><div class="d-flex flex-wrap gap-1">@if($record->verified==1 && !$record->uploaded_to_webpro)<form method="post" action="{{ route('modules.health-service-purchase.webpro',$record->id) }}">@csrf<button class="btn btn-sm btn-outline-success" title="تم الرفع إلى WebPro"><i class="bi bi-upload"></i></button></form>@endif<a class="btn btn-sm btn-outline-danger" href="{{ route('modules.health-service-purchase.pdf',$record->id) }}"><i class="bi bi-file-pdf"></i></a>@foreach($attachments[$record->id] ?? [] as $attachment)<a class="btn btn-sm btn-outline-secondary" href="{{ route('modules.health-service-purchase.download',[$record->id,$attachment->id]) }}"><i class="bi bi-paperclip"></i></a>@endforeach</div><form class="d-flex gap-1 mt-2" method="post" enctype="multipart/form-data" action="{{ route('modules.health-service-purchase.attachment',$record->id) }}">@csrf<input class="form-control form-control-sm" type="file" name="file" required><button class="btn btn-sm btn-outline-primary">رفع</button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-5">لا توجد بيانات</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $records->links() }}</div></div>
@endsection
