@extends('layouts.app')
@section('title', $definition['title'].' #'.$record->id)
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h4 mb-1">{{ $definition['title'] }} #{{ $record->id }}</h1><a href="{{ route('modules.emergency-reception.index', $type) }}">العودة إلى القائمة</a></div><a class="btn btn-outline-danger" href="{{ route('modules.emergency-reception.pdf', [$type,$record->id]) }}"><i class="bi bi-file-pdf"></i> PDF / طباعة</a></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="row g-3">@foreach($definition['fields'] as $field => [$label])<div class="col-md-6"><div class="text-muted small">{{ $label }}</div><div class="fw-semibold">{{ in_array($definition['fields'][$field][1], ['date','datetime-local'], true) && is_numeric($record->$field) ? date('Y-m-d H:i', (int)$record->$field) : ($record->$field ?? '—') }}</div></div>@endforeach</div></div></div>
@if($type==='incident')<div class="card border-0 shadow-sm mb-4"><div class="card-header"><strong>رفع التقرير الطبي</strong></div><form method="post" action="{{ route('modules.emergency-reception.medical-report',$record->id) }}"><div class="card-body row g-3">@csrf<div class="col-md-4"><label class="form-label">اسم الطبيب</label><select class="form-select" name="doctor_id" required>@foreach($lookups['doctors'] as $doctor)<option value="{{ $doctor->id }}" @selected($record->doctor_name==$doctor->id)>{{ $doctor->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">التشخيص الطبي</label><textarea class="form-control" name="medical_diagnosis" required>{{ $record->medical_diagnosis }}</textarea></div><div class="col-md-4"><label class="form-label">التوصية</label><textarea class="form-control" name="recommendation" required>{{ $record->recommendation }}</textarea></div></div><div class="card-footer bg-transparent"><button class="btn btn-primary">حفظ التقرير</button></div></form></div>@endif
@if($definition['attachments'])<div class="card border-0 shadow-sm"><div class="card-header"><strong>المرفقات</strong></div><div class="card-body"><form method="post" enctype="multipart/form-data" action="{{ route('modules.emergency-reception.attachment', [$type,$record->id]) }}" class="d-flex gap-2 mb-3">@csrf<input class="form-control" type="file" name="file" required accept=".jpg,.jpeg,.png,.gif,.pdf,.docx"><button class="btn btn-primary">رفع</button></form>@forelse($attachments as $attachment)<a class="btn btn-sm btn-outline-secondary me-2" href="{{ route('modules.emergency-reception.download', [$type,$record->id,$attachment->id]) }}"><i class="bi bi-paperclip"></i> {{ $attachment->file_name }}</a>@empty<p class="text-muted mb-0">لا توجد مرفقات</p>@endforelse</div></div>@endif
@endsection
