@extends('layouts.app')
@section('title', $row ? 'تعديل إقرار التنويم' : 'إقرار تنويم جديد')
@section('content')
<div class="container-fluid py-3" dir="rtl"><div class="card border-0 shadow-sm"><div class="card-body"><h1 class="h4 mb-4">{{ $row ? 'تعديل إقرار التنويم' : 'إقرار تنويم جديد' }}</h1>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="post" action="{{ $row ? route('modules.admission-inpatient.consents.update',$row->id) : route('modules.admission-inpatient.consents.store') }}">@csrf @if($row) @method('PUT') @endif
<div class="row g-3">
    <div class="col-md-6"><label class="form-label">اسم المريض بالعربي</label><input class="form-control" name="patient_name_ar" value="{{ old('patient_name_ar',$row->patient_name_ar ?? '') }}"></div>
    <div class="col-md-6"><label class="form-label">Patient name</label><input class="form-control" name="patient_name_en" value="{{ old('patient_name_en',$row->patient_name_en ?? '') }}"></div>
    <div class="col-md-4"><label class="form-label">هوية المريض</label><input class="form-control" name="patient_idno" required value="{{ old('patient_idno',$row->patient_idno ?? '') }}"></div>
    <div class="col-md-4"><label class="form-label">نوع هوية المريض</label><select class="form-select" name="patient_id_type"><option value="">اختر</option>@foreach($idTypes as $item)<option value="{{ $item->id }}" @selected((int)old('patient_id_type',$row->pateintIDType ?? 0)===(int)$item->id)>{{ $item->name_ar ?? $item->name_en ?? $item->DESCRIPTION ?? $item->id }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">رقم الملف</label><input class="form-control" name="patient_file_number" required value="{{ old('patient_file_number',$row->patient_file_number ?? '') }}"></div>
    <div class="col-md-4"><label class="form-label">جنسية المريض</label><select class="form-select" name="patient_nationality" required><option value="">اختر</option>@foreach($countries as $country)<option value="{{ $country->id ?? '' }}" @selected((string)old('patient_nationality',$row->patient_nationality ?? '') === (string)($country->id ?? ''))>{{ $country->DESCRIPTION ?? $country->name_ar ?? $country->name_en ?? '' }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">تاريخ الميلاد</label><div class="input-group"><input class="form-control" type="number" min="1" max="31" name="birth_day" placeholder="اليوم" value="{{ old('birth_day',$row->birth_day ?? '') }}"><input class="form-control" type="number" min="1" max="12" name="birth_month" placeholder="الشهر" value="{{ old('birth_month',$row->birth_month ?? '') }}"><input class="form-control" type="number" min="1900" max="2100" name="birth_year" placeholder="السنة" value="{{ old('birth_year',$row->birth_year ?? '') }}"></div></div>
    <div class="col-md-4"><label class="form-label">الجنس</label><select class="form-select" name="sex_code"><option value="0">غير محدد</option><option value="1" @selected((int)old('sex_code',$row->sexCode ?? 0)===1)>ذكر</option><option value="2" @selected((int)old('sex_code',$row->sexCode ?? 0)===2)>أنثى</option></select></div>
    <div class="col-md-4"><label class="form-label">نوع المتعهد</label><select class="form-select" name="contractor_type" id="contractor-type"><option value="1" @selected((int)old('contractor_type',$row->contractor_type ?? 1)===1)>متعهد آخر</option><option value="2" @selected((int)old('contractor_type',$row->contractor_type ?? 1)===2)>المريض أصالة عن نفسه</option></select></div>
    <div class="col-md-4"><label class="form-label">اسم المتعهد عربي</label><input class="form-control contractor-field" name="contractor_name_ar" value="{{ old('contractor_name_ar',$row->contractor_name_ar ?? '') }}"></div>
    <div class="col-md-4"><label class="form-label">اسم المتعهد English</label><input class="form-control" name="contractor_name_en" value="{{ old('contractor_name_en',$row->contractor_name_en ?? '') }}"></div>
    <div class="col-md-4"><label class="form-label">هوية المتعهد</label><input class="form-control contractor-field" name="contractor_idno" value="{{ old('contractor_idno',$row->contractor_idno ?? '') }}"></div>
    <div class="col-md-4"><label class="form-label">نوع هوية المتعهد</label><select class="form-select" name="contractor_id_type"><option value="">اختر</option>@foreach($idTypes as $item)<option value="{{ $item->id }}" @selected((int)old('contractor_id_type',$row->contractorIDType ?? 0)===(int)$item->id)>{{ $item->name_ar ?? $item->name_en ?? $item->id }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">جنسية المتعهد</label><select class="form-select" name="contractor_nationality"><option value="">اختر</option>@foreach($countries as $country)<option value="{{ $country->id ?? '' }}" @selected((string)old('contractor_nationality',$row->contractor_nationality ?? '') === (string)($country->id ?? ''))>{{ $country->DESCRIPTION ?? $country->name_ar ?? $country->name_en ?? '' }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">جوال المتعهد</label><input class="form-control" name="contractor_mobile" required pattern="05[0-9]{8}" maxlength="10" value="{{ old('contractor_mobile',$row->contractor_mobile ?? '') }}"></div>
    <div class="col-md-4"><label class="form-label">صلة القرابة</label><select class="form-select contractor-field" name="relative"><option value="">اختر</option>@foreach($relatives as $relative)<option value="{{ $relative->id }}" @selected((int)old('relative',$row->relative ?? 0)===(int)$relative->id)>{{ $relative->name_ar ?? $relative->name_en ?? $relative->id }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">لغة الإقرار</label><select class="form-select" name="language"><option value="1" @selected((int)old('language',$row->language ?? ($language ?? 1))===1)>العربية</option><option value="2" @selected((int)old('language',$row->language ?? ($language ?? 1))===2)>English</option></select></div>
    <div class="col-md-4"><label class="form-label">طريقة الدفع</label><input class="form-control" type="number" min="0" name="payment_type" value="{{ old('payment_type',$row->payment_type ?? 0) }}"></div>
    <div class="col-md-4"><label class="form-label">المبلغ المستحق</label><input class="form-control" type="number" min="0" step="0.01" name="deserved_amount" value="{{ old('deserved_amount',$row->deserved_amount ?? 0) }}"></div>
    <div class="col-md-4"><label class="form-label">المبلغ المدفوع</label><input class="form-control" type="number" min="0" step="0.01" name="paid_amount" value="{{ old('paid_amount',$row->paid_amount ?? 0) }}"></div>
    <div class="col-md-6"><label class="form-label">قالب الإقرار</label><select class="form-select" id="consent-template" name="template_id"><option value="">بدون قالب</option>@foreach($templates as $template)<option value="{{ $template->id }}" data-title="{{ e($template->title) }}" data-content="{{ e($template->consent_content) }}" @selected((string)old('template_id')===(string)$template->id)>{{ $template->title }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">عنوان الإقرار</label><input class="form-control" name="consent_title" id="consent-title" required value="{{ old('consent_title',$row->title ?? '') }}"></div>
    <div class="col-md-6"><label class="form-label">مديرو المناوبة للإشعار</label><select class="form-select" name="duty_managers_ids[]" multiple size="4">@foreach($managers as $manager)<option value="{{ $manager->hr_id }}">{{ trim(($manager->hr_first_name ?? '').' '.($manager->hr_last_name ?? '')) }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">البريد الإلكتروني</label><input class="form-control" type="email" name="email" value="{{ old('email',$row->email ?? '') }}"></div>
    <div class="col-12"><label class="form-label">نص الإقرار</label><textarea class="form-control" rows="8" name="consent_content" id="consent-content" required>{{ old('consent_content',$row->consent_content ?? '') }}</textarea></div>
</div><button class="btn btn-primary mt-4">حفظ الإقرار</button></form>
</div></div></div>
<script>
document.getElementById('consent-template')?.addEventListener('change', function(){ const option=this.options[this.selectedIndex]; if(option.dataset.title){document.getElementById('consent-title').value=option.dataset.title; document.getElementById('consent-content').value=option.dataset.content||'';} });
document.getElementById('contractor-type')?.addEventListener('change', function(){document.querySelectorAll('.contractor-field').forEach(el=>el.disabled=this.value==='2');});
</script>
@endsection
