@extends('layouts.app')
@section('title', 'اتفاقية تقديم خدمات طبية جديدة')
@section('content')
<div class="card border-0 shadow-sm"><div class="card-body"><h1 class="h5 mb-4">اتفاقية تقديم خدمات طبية جديدة</h1><form method="post" action="{{ route('modules.medical-agreements.store',$variant) }}">@csrf
<div class="row g-3"><div class="col-md-3"><label class="form-label">اللغة</label><select class="form-select" name="language" required><option value="1">العربية</option><option value="2">English</option></select></div><div class="col-md-3"><label class="form-label">صفة المتعهد</label><select class="form-select" name="contractor_type" required><option value="2">المريض نفسه</option><option value="1">متعهد بالنيابة</option></select></div><div class="col-md-3"><label class="form-label">نوع هوية المريض</label><select class="form-select" name="patient_id_type"><option value="0">—</option>@foreach($idTypes as $item)<option value="{{ $item->id }}">{{ $item->name_ar }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">الجنس</label><select class="form-select" name="sex_code"><option value="0">—</option><option value="1">ذكر</option><option value="2">أنثى</option></select></div>
<div class="col-md-6"><label class="form-label">اسم المريض بالعربية</label><input class="form-control" name="patient_name_ar" value="{{ old('patient_name_ar') }}"></div><div class="col-md-6"><label class="form-label">اسم المريض بالإنجليزية</label><input class="form-control" dir="ltr" name="patient_name_en" value="{{ old('patient_name_en') }}"></div><div class="col-md-4"><label class="form-label">رقم الهوية</label><input class="form-control" name="patient_idno" maxlength="12" required></div><div class="col-md-4"><label class="form-label">رقم الملف الطبي</label><input class="form-control" name="patient_file_number" maxlength="20" required></div><div class="col-md-4"><label class="form-label">جنسية المريض</label><select class="form-select" name="patient_nationality" required>@foreach($countries as $country)<option value="{{ $country->CODE }}">{{ $country->DESCRIPTION }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">اسم المتعهد بالعربية</label><input class="form-control" name="contractor_name_ar"></div><div class="col-md-6"><label class="form-label">اسم المتعهد بالإنجليزية</label><input class="form-control" dir="ltr" name="contractor_name_en"></div><div class="col-md-3"><label class="form-label">نوع هوية المتعهد</label><select class="form-select" name="contractor_id_type"><option value="0">—</option>@foreach($idTypes as $item)<option value="{{ $item->id }}">{{ $item->name_ar }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">هوية المتعهد</label><input class="form-control" name="contractor_idno"></div><div class="col-md-3"><label class="form-label">جوال المتعهد</label><input class="form-control" name="contractor_mobile" maxlength="16" required></div><div class="col-md-3"><label class="form-label">جنسية المتعهد</label><select class="form-select" name="contractor_nationality"><option value="">—</option>@foreach($countries as $country)<option value="{{ $country->CODE }}">{{ $country->DESCRIPTION }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">صلة القرابة</label><select class="form-select" name="relative"><option value="0">بالأصالة عن نفسه</option>@foreach($relatives as $relative)<option value="{{ $relative->id }}">{{ $relative->name_ar }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">البريد الإلكتروني</label><input class="form-control" type="email" name="email"></div><div class="col-md-4"><label class="form-label">نوع التاريخ</label><select class="form-select" name="date_type"><option value="1">هجري</option><option value="2">ميلادي</option></select></div><div class="col-md-4"><label class="form-label">يوم الميلاد</label><input class="form-control" type="number" min="1" max="31" name="birth_day"></div><div class="col-md-4"><label class="form-label">شهر الميلاد</label><input class="form-control" type="number" min="1" max="12" name="birth_month"></div><div class="col-md-4"><label class="form-label">سنة الميلاد</label><input class="form-control" type="number" name="birth_year"></div></div>
@if($errors->any())<div class="alert alert-danger mt-3">{{ $errors->first() }}</div>@endif<button class="btn btn-primary mt-4" type="submit"><i class="bi bi-check-lg"></i> حفظ</button></form></div></div>
@endsection
