@extends('layouts.app')
@section('title', 'اتفاقيات تقديم الخدمات الطبية')
@section('content')
@php($titles=['standard'=>'اتفاقية تقديم خدمات طبية','sadq'=>'اتفاقية تقديم خدمات طبية — صادق','sadq-manual'=>'اتفاقية تقديم خدمات طبية — صادق (إدخال يدوي)'])
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><h1 class="h4 mb-1">{{ $titles[$variant] }}</h1><p class="text-muted mb-0">السجلات المطابقة لنطاق الفرع والشركة الحاليين</p></div><a class="btn btn-primary" href="{{ route('modules.medical-agreements.create',$variant) }}"><i class="bi bi-plus-lg"></i> اتفاقية جديدة</a></div>
<form class="card border-0 shadow-sm mb-3" method="get"><div class="card-body row g-3 align-items-end">
<div class="col-md-2"><label class="form-label">من تاريخ</label><input class="form-control" type="date" name="from" value="{{ $filters['from'] }}"></div><div class="col-md-2"><label class="form-label">إلى تاريخ</label><input class="form-control" type="date" name="to" value="{{ $filters['to'] }}"></div>
<div class="col-md-2"><label class="form-label">الحالة</label><select class="form-select" name="status"><option value="">الكل</option>@if($variant==='standard')<option value="pending" @selected($filters['status']==='pending')>معلق</option><option value="authenticated" @selected($filters['status']==='authenticated')>تمت المصادقة</option>@else<option value="In-progress" @selected($filters['status']==='In-progress')>قيد التوقيع</option><option value="Completed" @selected($filters['status']==='Completed')>مكتمل</option><option value="Rejected" @selected($filters['status']==='Rejected')>مرفوض</option>@endif</select></div>
<div class="col-md-2"><label class="form-label">المدخل</label><select class="form-select" name="creator"><option value="">الكل</option>@foreach($creators as $creator)<option value="{{ $creator->hr_id }}" @selected($filters['creator']==(string)$creator->hr_id)>{{ $creator->hr_first_name }} {{ $creator->hr_last_name }}</option>@endforeach</select></div>
<div class="col-md-2"><label class="form-label">اللغة</label><select class="form-select" name="language"><option value="">الكل</option><option value="1" @selected($filters['language']==='1')>العربية</option><option value="2" @selected($filters['language']==='2')>English</option></select></div>
<div class="col-md-2"><label class="form-label">رقم الهوية</label><input class="form-control" name="id_number" value="{{ $filters['id_number'] }}"></div><div class="col-12 d-flex gap-2 justify-content-end"><a class="btn btn-outline-secondary" href="{{ route('modules.medical-agreements.index',$variant) }}">استعادة</a><button class="btn btn-primary"><i class="bi bi-search"></i> بحث</button></div>
</div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>التاريخ</th><th>اسم المريض</th><th>رقم الهوية</th><th>رقم الملف الطبي</th><th>مدخل البيانات</th><th>رقم هوية المتعهد</th><th>المستند</th><th>الخط الزمني</th></tr></thead><tbody>
@forelse($agreements as $agreement)<tr><td dir="ltr">{{ $agreement->created_at }}</td><td>{{ $agreement->patient_name_ar ?: $agreement->patient_name_en }}</td><td>{{ $agreement->patient_idno }}</td><td>{{ $agreement->patient_file_number }}</td><td>{{ $agreement->creator_name }}</td><td>{{ $agreement->contractor_idno }}</td><td><a class="btn btn-sm btn-outline-danger" href="{{ route('modules.medical-agreements.pdf',[$variant,$agreement->id]) }}"><i class="bi bi-file-earmark-pdf"></i> PDF</a></td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('modules.medical-agreements.show',[$variant,$agreement->id]) }}"><i class="bi bi-clock-history"></i></a></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-5">لا توجد سجلات</td></tr>@endforelse
</tbody></table></div><div class="p-3">{{ $agreements->links() }}</div></div>
@endsection
