<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><style>body{font-family:ArabicPdf,DejaVu Sans,sans-serif;font-size:12px;line-height:1.8;direction:rtl;color:#222}h1{text-align:center;font-size:20px;margin:0 0 16px}h2{font-size:14px;margin:12px 0 3px;color:#173b67}table{width:100%;border-collapse:collapse;margin:12px 0}td,th{border:1px solid #7c8794;padding:6px;vertical-align:top}th{background:#eef3f7;width:20%}.meta td{width:30%}.terms{line-height:2.1;text-align:justify}.english{direction:ltr;text-align:left;font-size:10px;color:#444}</style></head><body>
<h1>اتفاقية تقديم خدمات طبية<br><span class="english">Agreement for the Provision of Medical Services</span></h1>
<table><tr><th>اسم المريض</th><td>{{ $agreement->patient_name_ar ?: $agreement->patient_name_en }}</td><th>Patient name</th><td class="english">{{ $agreement->patient_name_en ?: $agreement->patient_name_ar }}</td></tr><tr><th>رقم الهوية</th><td>{{ $agreement->patient_idno }}</td><th>رقم الملف الطبي</th><td>{{ $agreement->patient_file_number }}</td></tr><tr><th>المتعهد</th><td>{{ $agreement->contractor_name_ar ?: $agreement->contractor_name_en }}</td><th>هوية المتعهد</th><td>{{ $agreement->contractor_idno }}</td></tr><tr><th>الجوال</th><td dir="ltr">{{ $agreement->contractor_mobile }}</td><th>البريد الإلكتروني</th><td dir="ltr">{{ $agreement->email ?: '—' }}</td></tr><tr><th>تاريخ الميلاد</th><td>{{ $agreement->birth_day }}-{{ $agreement->birth_month }}-{{ $agreement->birth_year }} — {{ (int) $agreement->date_type === 1 ? 'هجري' : 'ميلادي' }}</td><th>تاريخ الإنشاء</th><td dir="ltr">{{ $agreement->created_at }}</td></tr></table>
<div class="terms">
<h2>أولاً: الموافقة على تقديم الخدمات</h2><p>أوافق أنا الموقع أدناه على قيام مجموعة مستشفيات الحمادي وطاقمها الطبي بتقديم الفحوصات والعلاجات والخدمات الصحية المناسبة للمريض المذكور، وفقاً لتقدير الفريق المعالج والأصول الطبية والأنظمة المعمول بها.</p>
<h2>ثانياً: المسؤولية المالية</h2><p>أقر بأنني المتعهد عن المريض، وأتحمل كامل المسؤولية المالية والقانونية عن تكاليف الخدمات الطبية المقدمة، سواء كنت مستفيداً من الخدمة أو أطلب تقديمها للمريض المذكور، وذلك دون إخلال بأي حق نظامي تجاه جهة ضامنة أو طرف ثالث.</p>
<h2>ثالثاً: صحة البيانات</h2><p>أقر بصحة واكتمال البيانات المدونة في هذه الاتفاقية، وأتعهد بإبلاغ المستشفى عن أي تغيير يطرأ عليها، وأتحمل مسؤولية أي خطأ أو نقص فيها.</p>
<h2>رابعاً: التأمين والجهات الضامنة</h2><p>أفوض المستشفى في التحقق من أهلية التغطية التأمينية والتواصل مع الجهات الضامنة، وأوافق على أن أي خدمة غير مغطاة أو مرفوضة تكون على مسؤوليتي وفق الأسعار والسياسات المعتمدة.</p>
<h2>خامساً: الإفصاح عن المعلومات</h2><p>أوافق على استخدام البيانات الصحية والشخصية بالقدر اللازم لتقديم الرعاية، وإدارة المطالبات، والالتزام بمتطلبات الجهات الحكومية والتنظيمية، مع مراعاة الأنظمة ذات العلاقة بحماية البيانات.</p>
<h2>سادساً: التواصل والإشعارات</h2><p>أوافق على استخدام رقم الجوال والبريد الإلكتروني الموضحين للتواصل وإرسال الإشعارات المتعلقة بالخدمات والطلبات والتوقيع الإلكتروني.</p>
<h2>سابعاً: تعليمات الفريق الطبي</h2><p>أتعهد بإعطاء المعلومات الطبية الصحيحة واتباع تعليمات الأطباء والتمريض، وأفهم أن النتائج الطبية لا يمكن ضمانها رغم بذل العناية المهنية اللازمة.</p>
<h2>ثامناً: القاصر أو من يمثله</h2><p>إذا كان التوقيع نيابة عن المريض، أقر بأن لدي الصفة والصلاحية اللازمة للتعهد عنه، وأتحمل مسؤولية صحة هذه الصفة.</p>
<h2>تاسعاً: الإلغاء والتعديل</h2><p>لا يعتد بأي تعديل يدوي على هذه الوثيقة بعد إصدارها، وأي تعديل أو إلغاء يكون من خلال النظام أو الجهة المختصة وبما لا يتعارض مع الخدمات التي تم تقديمها.</p>
<h2>عاشراً: الإقرار النهائي</h2><p>قرأت البنود السابقة وفهمتها ووافقت عليها، وأقر بأن هذه الاتفاقية تمثل تعهدي الملزم تجاه مجموعة مستشفيات الحمادي في حدود الأنظمة المرعية.</p>
<h2>الحادي عشر: التوقيع الإلكتروني</h2><p>أقر بأن توقيعي على هذه الاتفاقية يتم من خلال منصة صادق/إمضاء المعتمدة، ويعد توقيعاً صحيحاً وملزماً بكامل آثاره النظامية، وله الحجية النظامية المقررة للتوقيع الخطي وفق نظام التعاملات الإلكترونية السعودي ولائحته التنفيذية.</p>
</div><table class="meta"><tr><th>اسم المتعهد</th><td>{{ $agreement->contractor_name_ar ?: $agreement->contractor_name_en }}</td><th>رقم الهوية</th><td>{{ $agreement->contractor_idno }}</td></tr><tr><th>مرجع الاتفاقية</th><td>{{ $agreement->reference_number ?? '—' }}</td><th>مدخل البيانات</th><td>{{ $agreement->creator_name ?? '' }} {{ $agreement->creator_last_name ?? '' }}</td></tr></table>
</body></html>
