@extends('layouts.app')
@section('title', 'إرسال - '.$spec['label'])
@section('figma_page_header', 'true')
@push('workflow_styles')
    <link href="{{ asset('css/hm-figma-workflows.css') }}?v={{ filemtime(public_path('css/hm-figma-workflows.css')) }}" rel="stylesheet">
@endpush
@section('content')
<div class="hm-fm hm-workflow" dir="rtl">@include('layouts.partials.figma-module-header', ['crumbs' => [['label' => 'الخدمات التشغيلية'], ['label' => $spec['label']]], 'title' => 'إرسال رسالة جوال', 'subtitle' => 'إرسال الرسالة وتسجيلها في أرشيف الفرع', 'heroIconSrc' => asset('images/figma/workflows/references.svg'), 'heroIconSize' => 32, 'actionUrl' => route('modules.legacy-sidebar.index', $page), 'actionLabel' => 'رجوع', 'actionIconSrc' => asset('images/figma/technical-failures/add.svg')])
@if($errors->any())<div class="alert alert-danger mt-3">{{ $errors->first() }}</div>@endif
<form class="card border-0 shadow-sm" method="post" action="{{ route('modules.legacy-sidebar.compose.store', $page) }}">@csrf<div class="card-body row g-3"><div class="col-12"><label class="form-label">أرقام الجوال</label><textarea class="form-control" name="mobile" rows="4" placeholder="رقم واحد في كل سطر أو افصل بينها بفاصلة" required>{{ old('mobile') }}</textarea><div class="form-text">يمكن إدخال أكثر من رقم، وسيتم حذف الأرقام المكررة تلقائيًا.</div></div><div class="col-12"><label class="form-label">نص الرسالة</label><textarea class="form-control" name="message" rows="6" maxlength="1000" required>{{ old('message') }}</textarea></div>@if($senders !== [])<div class="col-md-4"><label class="form-label">اسم المرسل</label><select class="form-select" name="sender">@foreach($senders as $sender)<option value="{{ $sender }}" @selected(old('sender') === $sender)>{{ $sender }}</option>@endforeach</select></div>@endif<div class="col-md-4"><label class="form-label">نوع الرسالة</label><input class="form-control" type="number" min="0" name="type" value="{{ old('type', 0) }}"></div><div class="col-md-4"><label class="form-label">اللغة</label><select class="form-select" name="language"><option value="1" @selected(old('language', 1) == 1)>العربية</option><option value="2" @selected(old('language') == 2)>English</option></select></div></div><div class="card-footer text-start"><button class="btn btn-primary"><i class="bi bi-send"></i> إرسال</button></div></form></div>
@endsection
