@extends('layouts.app')
@section('title', 'تفاصيل قضية المطالبة المالية')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
 <div><h1 class="h4 mb-1">قضية المطالبة المالية: {{ $record->patient_name }}</h1><p class="text-muted mb-0">رقم الملف: {{ $record->file_number }} — الحالة: {{ $record->status_name_ar ?: $record->status }}</p></div>
 <div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-primary" target="_blank" href="{{ route('modules.legal-claims.claim-sheet-pdf', $record->id) }}">صحيفة الدعوى</a><a class="btn btn-outline-primary" target="_blank" href="{{ route('modules.legal-claims.pdf', $record->id) }}">PDF تفاصيل القضية</a><a class="btn btn-outline-secondary" href="{{ route('modules.legal-claims.index') }}">رجوع</a></div>
</div>
<div class="row g-3">
 <div class="col-lg-4">
  <div class="card border-0 shadow-sm"><div class="card-header">ملخص القضية</div><div class="card-body"><dl class="row mb-0"><dt class="col-6">رقم الهوية</dt><dd class="col-6">{{ $record->patient_idno ?: '—' }}</dd><dt class="col-6">المتعهد</dt><dd class="col-6">{{ $record->liable_name ?: '—' }}</dd><dt class="col-6">جوال المتعهد</dt><dd class="col-6" dir="ltr">{{ $record->liable_mobile ?: '—' }}</dd><dt class="col-6">المبلغ المتبقي</dt><dd class="col-6">{{ $record->amount_rest ?: '—' }}</dd><dt class="col-6">المبلغ المغطى</dt><dd class="col-6">{{ $record->covered_amount ?: '—' }}</dd><dt class="col-6">رقم القضية</dt><dd class="col-6">{{ $record->case_number ?: '—' }}</dd></dl></div></div>
  <div class="card border-0 shadow-sm mt-3"><div class="card-header">المستندات والمرفقات</div><div class="card-body"><p class="small text-muted">المستندات المطلوبة في الطلب</p><ul class="list-group list-group-flush mb-3">@for($file = 1; $file <= 4; $file++)<li class="list-group-item px-0 d-flex justify-content-between"><span>الملف المطلوب {{ $file }}</span>@if($record->{'file_'.$file})<a href="{{ route('modules.legal-claims.download', [$record->id, 'claim', $file]) }}">تنزيل</a>@else<span class="text-danger">غير مكتمل</span>@endif</li>@endfor</ul><form method="post" enctype="multipart/form-data" action="{{ route('modules.legal-claims.attachments.store', $record->id) }}">@csrf<label class="form-label">إرفاق مستند عام</label><div class="input-group"><input class="form-control" type="file" name="file" required><button class="btn btn-outline-primary">إرفاق</button></div></form><ul class="list-group list-group-flush mt-3">@foreach($record->attachments as $attachment)<li class="list-group-item px-0"><a href="{{ route('modules.legal-claims.download', [$record->id, 'attachment', $attachment->id]) }}">{{ basename($attachment->file_name) }}</a></li>@endforeach</ul></div></div>
 </div>
 <div class="col-lg-8">
  <div class="card border-0 shadow-sm mb-3"><div class="card-header">تحديث حالة القضية والجلسة</div><form method="post" enctype="multipart/form-data" action="{{ route('modules.legal-claims.actions.store', $record->id) }}">@csrf<div class="card-body row g-3"><div class="col-md-4"><label class="form-label">الحالة *</label><select class="form-select" name="status_id" required>@foreach($statuses as $status)<option value="{{ $status->id }}">{{ $status->name_ar }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">مقدم الطلب</label><input class="form-control" name="applicant"></div><div class="col-md-4"><label class="form-label">رقم الطلب</label><input class="form-control" name="request_number"></div><div class="col-md-4"><label class="form-label">تاريخ الطلب</label><input class="form-control" type="date" name="request_date"></div><div class="col-md-4"><label class="form-label">رقم الدعوى</label><input class="form-control" name="case_number"></div><div class="col-md-4"><label class="form-label">رقم الجلسة</label><input class="form-control" name="sessions_number"></div><div class="col-md-6"><label class="form-label">تاريخ الجلسة</label><input class="form-control" type="date" name="sessions_date"></div><div class="col-md-6"><label class="form-label">تاريخ الجلسة القادمة</label><input class="form-control" type="date" name="next_sessions_date"></div><div class="col-12"><label class="form-label">ملخص الإجراء أو الجلسة</label><textarea class="form-control" name="details" rows="2"></textarea></div><div class="col-md-4"><label class="form-label">ملف الطلب</label><input class="form-control" type="file" name="lawsuit_request_file"></div><div class="col-md-4"><label class="form-label">ملف الجلسة</label><input class="form-control" type="file" name="session_1_file"></div><div class="col-md-4"><label class="form-label">صك الحكم</label><input class="form-control" type="file" name="judgment_instrument"></div></div><div class="card-footer text-start"><button class="btn btn-primary">حفظ الإجراء</button></div></form></div>
  <div class="card border-0 shadow-sm mb-3"><div class="card-header">الجلسات السابقة والقادمة والخط الزمني</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>الحالة</th><th>الجلسة</th><th>القادمة</th><th>الملخص</th><th>الملفات</th></tr></thead><tbody>@forelse($record->actions as $action)<tr><td>{{ $action->status_name_ar ?: 'إجراء' }}</td><td>{{ $action->sessions_date ?: '—' }}</td><td>{{ $action->next_sessions_date ?: '—' }}</td><td>{{ $action->session_summary ?: $action->details ?: '—' }}</td><td>@if($action->lawsuit_request_file)<a href="{{ route('modules.legal-claims.download', [$record->id, 'action', $action->id]) }}">الطلب</a>@endif @if($action->session_1_file)<a href="{{ route('modules.legal-claims.download', [$record->id, 'session', $action->id]) }}">الجلسة</a>@endif @if(isset($action->judgment_instrument) && $action->judgment_instrument)<a href="{{ route('modules.legal-claims.download', [$record->id, 'judgment', $action->id]) }}">صك الحكم</a>@endif</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">لا توجد جلسات أو إجراءات مسجلة.</td></tr>@endforelse</tbody></table></div></div>
  <div class="card border-0 shadow-sm mb-3"><div class="card-header">طلبات الإفادة</div><div class="card-body"><form method="post" enctype="multipart/form-data" action="{{ route('modules.legal-claims.statements.store', $record->id) }}">@csrf<div class="row g-2"><div class="col-md-8"><label class="form-label">تفاصيل طلب الإفادة *</label><input class="form-control" name="details" required></div><div class="col-md-4"><label class="form-label">المرفق</label><input class="form-control" type="file" name="file"></div></div><button class="btn btn-outline-primary mt-3">إنشاء طلب إفادة</button></form><div class="table-responsive mt-3"><table class="table table-sm"><thead><tr><th>المرسل</th><th>الفرع المستلم</th><th>التاريخ</th><th>التفاصيل</th><th>المرفق</th></tr></thead><tbody>@forelse($record->statements as $statement)<tr><td>{{ $statement->created_by }}</td><td>{{ $statement->branch_id }}</td><td>{{ $statement->created_at }}</td><td>{{ $statement->details }}</td><td>@if($statement->file)<a href="{{ route('modules.legal-claims.download', [$record->id, 'statement', $statement->id]) }}">تنزيل</a>@else — @endif</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">لا توجد طلبات إفادة.</td></tr>@endforelse</tbody></table></div></div></div>
 </div>
</div>
<div class="row g-3 mt-1"><div class="col-lg-6"><div class="card border-0 shadow-sm"><div class="card-header">طلب التنازل</div><form method="post" enctype="multipart/form-data" action="{{ route('modules.legal-claims.suspensions.store', $record->id) }}">@csrf<div class="card-body row g-2"><div class="col-md-4"><select class="form-select" name="status_id" required>@foreach($suspensionStatuses as $status)<option value="{{ $status->id }}">{{ $status->name_ar }}</option>@endforeach</select></div><div class="col-md-4"><input class="form-control" name="total_amount" type="number" step="0.01" placeholder="إجمالي المبلغ"></div><div class="col-md-4"><input class="form-control" name="amount_waived" type="number" step="0.01" placeholder="المبلغ المتنازل عنه"></div><div class="col-12"><input class="form-control" type="file" name="file"></div></div><div class="card-footer text-start"><button class="btn btn-outline-primary">حفظ طلب التنازل</button> <a class="btn btn-link" target="_blank" href="{{ route('modules.legal-claims.suspension-pdf', $record->id) }}">PDF الطلبات</a></div></form><ul class="list-group list-group-flush">@foreach($record->suspensions as $suspension)<li class="list-group-item">{{ $suspension->status_name_ar }} — {{ $suspension->amount_waived }} @if($suspension->file)<a class="ms-2" href="{{ route('modules.legal-claims.download', [$record->id, 'waiver', $suspension->id]) }}">المرفق</a>@endif</li>@endforeach</ul></div></div>
<div class="col-lg-6"><div class="card border-0 shadow-sm"><div class="card-header">جدول الأقساط والسداد</div><div class="card-body"><form class="row g-2 mb-3" method="post" action="{{ route('modules.legal-claims.installments.store', $record->id) }}">@csrf<div class="col"><input class="form-control" type="date" name="installment_date" required></div><div class="col-auto"><button class="btn btn-outline-primary">إضافة قسط</button></div></form>@forelse($record->installments as $installment)<div class="d-flex justify-content-between border-top py-2"><span>{{ $installment->installment_date }}</span>@if($installment->payment_status)<span class="text-success">تم السداد: {{ $installment->payment_date }}</span>@else<form method="post" action="{{ route('modules.legal-claims.installments.paid', [$record->id, $installment->id]) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-primary">تأكيد السداد</button></form>@endif</div>@empty<p class="text-muted mb-0">لا توجد أقساط.</p>@endforelse</div></div></div></div>
@endsection
