<?php

use App\Support\CorporateCommunications\CorporateCommunicationPermissions;
use App\Support\EmployeeLeave\EmployeeLeavePermissions;
use App\Support\MedicalAppointments\MedicalAppointmentScope;
use App\Support\Training\TrainingPermissions;

return [

    // Application release version. Bump on each deployment so the login
    // screen shows the currently uploaded build (used to diff future upgrades).
    'version' => env('HM_APP_VERSION', '1.0.5'),

    'otp' => [
        'length' => max(4, min(8, (int) env('HM_OTP_LENGTH', 6))),
        'expiry_seconds' => (int) env('HM_OTP_EXPIRY_SECONDS', 300),
        'resend_cooldown_seconds' => (int) env('HM_OTP_RESEND_COOLDOWN_SECONDS', 30),
        'max_attempts' => (int) env('HM_OTP_MAX_ATTEMPTS', 5),
        'demo_mode' => (bool) env('HM_OTP_DEMO_MODE', false),
    ],

    'password_recovery' => [
        'otp_length' => 6,
        'expiry_seconds' => 120,
        'max_attempts' => 5,
        'authorization_seconds' => 300,
    ],

    'permissions' => [
        'bypass' => (bool) env('HM_PERMISSIONS_BYPASS', false),
        'admin_levels' => [3],
        'enforcement_mode' => env('HM_PERMISSION_ENFORCEMENT_MODE', 'compat'),
    ],

    'dashboard' => [
        'widgets' => [
            [
                'label_key' => 'modules',
                'source' => 'module_count',
                'icon' => 'bi-grid',
                'variant' => 'primary',
            ],
            [
                'label_key' => 'navigation',
                'source' => 'nav_count',
                'icon' => 'bi-list-ul',
                'variant' => 'success',
            ],
            [
                'label_key' => 'role',
                'source' => 'user_level',
                'icon' => 'bi-shield-check',
                'variant' => 'info',
            ],
        ],
        'cards' => [
            [
                'label_key' => 'doctors',
                'route' => 'modules.doctors',
                'icon' => 'bi-person-vcard',
            ],
            [
                'label_key' => 'system_administration',
                'route' => 'modules.system-admin.dashboard',
                'icon' => 'bi-shield-lock',
                'admin_only' => true,
            ],
            [
                'label_key' => 'clinics',
                'route' => 'modules.service-locations.index',
                'icon' => 'bi-building',
            ],
            [
                'label_key' => 'hospital_services',
                'route' => 'modules.hospital-services',
                'icon' => 'bi-hospital',
            ],
            [
                'label_key' => 'complaints',
                'route' => 'modules.complaints',
                'icon' => 'bi-chat-square-text',
                'permission' => 'complaints',
            ],
            [
                'label_key' => 'employee_services',
                'route' => 'modules.employee-services',
                'icon' => 'bi-person-workspace',
            ],
        ],
    ],

    'navigation' => [
        'sidebar' => [
            ['label_key' => 'dashboard', 'route' => 'dashboard', 'icon' => 'bi-speedometer2', 'active_prefix' => 'dashboard', 'subtitle_key' => 'dashboard.title'],
            ['label_key' => 'doctors', 'route' => 'modules.doctors', 'icon' => 'bi-person-vcard', 'active_prefix' => 'modules.doctors', 'subtitle_key' => 'doctors_directory.subtitle'],
            ['label_key' => 'clinics', 'route' => 'modules.service-locations.index', 'icon' => 'bi-building', 'active_prefix' => 'modules.service-locations.', 'subtitle_key' => 'service_locations.subtitle'],
            [
                'type' => 'group',
                'label_key' => 'service_location_details',
                'icon' => 'bi-geo-alt',
                'user_levels' => [1, 2, 4],
                'children' => [
                    ['label_key' => 'service_location_opd_1', 'route' => 'modules.service-locations.show', 'route_params' => ['outpatientClinic' => 1], 'icon' => 'bi-building', 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'service_location_opd_2', 'route' => 'modules.service-locations.show', 'route_params' => ['outpatientClinic' => 2], 'icon' => 'bi-building', 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'service_location_opd_3', 'route' => 'modules.service-locations.show', 'route_params' => ['outpatientClinic' => 3], 'icon' => 'bi-building', 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'service_location_opd_4', 'route' => 'modules.service-locations.show', 'route_params' => ['outpatientClinic' => 4], 'icon' => 'bi-building', 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'service_location_opd_5', 'route' => 'modules.service-locations.show', 'route_params' => ['outpatientClinic' => 5], 'icon' => 'bi-building', 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'service_location_opd_6', 'route' => 'modules.service-locations.show', 'route_params' => ['outpatientClinic' => 6], 'icon' => 'bi-building', 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'service_location_opd_7', 'route' => 'modules.service-locations.show', 'route_params' => ['outpatientClinic' => 7], 'icon' => 'bi-building', 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'service_location_floors', 'route' => 'modules.service-locations.floors', 'icon' => 'bi-layers', 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'service_location_floor_1', 'route' => 'modules.service-locations.floors.show', 'route_params' => ['floor' => 1], 'icon' => 'bi-layers', 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'service_location_floor_2', 'route' => 'modules.service-locations.floors.show', 'route_params' => ['floor' => 2], 'icon' => 'bi-layers', 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'service_location_floor_3', 'route' => 'modules.service-locations.floors.show', 'route_params' => ['floor' => 3], 'icon' => 'bi-layers', 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'service_location_floor_4', 'route' => 'modules.service-locations.floors.show', 'route_params' => ['floor' => 4], 'icon' => 'bi-layers', 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'service_location_floor_5', 'route' => 'modules.service-locations.floors.show', 'route_params' => ['floor' => 5], 'icon' => 'bi-layers', 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'service_location_floor_6', 'route' => 'modules.service-locations.floors.show', 'route_params' => ['floor' => 6], 'icon' => 'bi-layers', 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'service_location_floor_7', 'route' => 'modules.service-locations.floors.show', 'route_params' => ['floor' => 7], 'icon' => 'bi-layers', 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'service_location_floor_8', 'route' => 'modules.service-locations.floors.show', 'route_params' => ['floor' => 8], 'icon' => 'bi-layers', 'user_levels' => [1, 2, 4]],
                ],
            ],
            [
                'type' => 'group',
                'label_key' => 'inquiries',
                'icon' => 'bi-chat-left-text',
                'children' => [
                    [
                        'label_key' => 'inquiries_outgoing',
                        'route' => 'modules.inquiries.outgoing.index',
                        'icon' => 'bi-send',
                        'active_prefix' => 'modules.inquiries.outgoing',
                        'active_params' => ['direction' => 'outgoing'],
                        'subtitle_key' => 'inquiries.subtitle',
                        'permission' => 'inquiries_and_services',
                    ],
                    [
                        'label_key' => 'inquiries_incoming',
                        'route' => 'modules.inquiries.incoming.index',
                        'icon' => 'bi-inbox',
                        'active_prefix' => 'modules.inquiries.incoming',
                        'active_params' => ['direction' => 'incoming'],
                        'subtitle_key' => 'inquiries.subtitle',
                        'permission' => 'inquiries_and_services',
                    ],
                ],
            ],
            [
                'type' => 'group',
                'label_key' => 'services',
                'icon' => 'bi-hospital',
                'children' => [
                    [
                        'label_key' => 'services_overview',
                        'route' => 'modules.hospital-services',
                        'icon' => 'bi-grid-3x3-gap',
                        'active_prefix' => 'modules.hospital-services',
                        'subtitle_key' => 'hospital_services.dashboard_subtitle',
                    ],
                    [
                        'label_key' => 'services_outpatient',
                        'route' => 'modules.services.sections.show',
                        'route_params' => ['section' => 1],
                        'icon' => 'bi-clipboard2-pulse',
                        'subtitle_key' => 'hospital_services.section_page_subtitle',
                    ],
                    [
                        'label_key' => 'services_radiology',
                        'route' => 'modules.services.sections.show',
                        'route_params' => ['section' => 2],
                        'icon' => 'bi-radioactive',
                        'subtitle_key' => 'hospital_services.section_page_subtitle',
                    ],
                    [
                        'label_key' => 'services_lab',
                        'route' => 'modules.services.sections.show',
                        'route_params' => ['section' => 3],
                        'icon' => 'bi-eyedropper',
                        'subtitle_key' => 'hospital_services.section_page_subtitle',
                    ],
                    [
                        'label_key' => 'services_physiotherapy',
                        'route' => 'modules.services.sections.show',
                        'route_params' => ['section' => 4],
                        'icon' => 'bi-heart-pulse',
                        'subtitle_key' => 'hospital_services.section_page_subtitle',
                    ],
                    [
                        'label_key' => 'services_inpatient',
                        'type' => 'group',
                        'icon' => 'bi-hospital',
                        'children' => [
                            [
                                'label_key' => 'services_inpatient_rooms',
                                'route' => 'modules.services.sections.show',
                                'route_params' => ['section' => 7],
                                'icon' => 'bi-door-open',
                                'active_prefix' => 'modules.services.sections',
                                'active_params' => ['section' => 7],
                                'subtitle_key' => 'hospital_services.section_page_subtitle',
                                'published_section_id' => 7,
                            ],
                            [
                                'label_key' => 'services_inpatient_reproduction',
                                'route' => 'modules.services.sections.show',
                                'route_params' => ['section' => 8],
                                'icon' => 'bi-heart-pulse',
                                'active_prefix' => 'modules.services.sections',
                                'active_params' => ['section' => 8],
                                'subtitle_key' => 'hospital_services.section_page_subtitle',
                                'published_section_id' => 8,
                                'excluded_company_ids' => [3],
                            ],
                            [
                                'label_key' => 'services_inpatient_endoscopy',
                                'route' => 'modules.services.sections.show',
                                'route_params' => ['section' => 9],
                                'icon' => 'bi-circle-half',
                                'active_prefix' => 'modules.services.sections',
                                'active_params' => ['section' => 9],
                                'subtitle_key' => 'hospital_services.section_page_subtitle',
                                'published_section_id' => 9,
                            ],
                            [
                                'label_key' => 'services_inpatient_dialysis',
                                'route' => 'modules.services.sections.show',
                                'route_params' => ['section' => 10],
                                'icon' => 'bi-droplet-half',
                                'active_prefix' => 'modules.services.sections',
                                'active_params' => ['section' => 10],
                                'subtitle_key' => 'hospital_services.section_page_subtitle',
                                'published_section_id' => 10,
                            ],
                        ],
                    ],
                    [
                        'label_key' => 'services_partnerships',
                        'route' => 'modules.services.sections.show',
                        'route_params' => ['section' => 11],
                        'icon' => 'bi-percent',
                        'subtitle_key' => 'hospital_services.section_page_subtitle',
                    ],
                    [
                        'label_key' => 'services_contracted_centers',
                        'route' => 'modules.services.sections.show',
                        'route_params' => ['section' => 12],
                        'icon' => 'bi-building',
                        'subtitle_key' => 'hospital_services.section_page_subtitle',
                    ],
                ],
            ],
            [
                'type' => 'group',
                'label_key' => 'inpatient_workflows',
                'icon' => 'bi-clipboard2-pulse',
                'children' => [
                    ['label_key' => 'inpatient_calculator', 'route' => 'modules.admission-inpatient.calculator.index', 'route_params' => ['type' => 'standard'], 'icon' => 'bi-calculator', 'active_prefix' => 'modules.admission-inpatient.calculator.'],
                    ['label_key' => 'inpatient_manual_calculator', 'route' => 'modules.admission-inpatient.calculator.index', 'route_params' => ['type' => 'manual'], 'icon' => 'bi-calculator-fill', 'active_prefix' => 'modules.admission-inpatient.calculator.'],
                    ['label_key' => 'inpatient_consents', 'route' => 'modules.admission-inpatient.consents.index', 'icon' => 'bi-file-earmark-check', 'active_prefix' => 'modules.admission-inpatient.consents', 'branch_ids' => [1, 9, 34]],
                    ['label_key' => 'inpatient_approvals', 'route' => 'modules.admission-inpatient.approvals.index', 'icon' => 'bi-send-check', 'active_prefix' => 'modules.admission-inpatient.approvals', 'branch_ids' => [10]],
                    ['label_key' => 'inpatient_doctors', 'route' => 'modules.admission-inpatient.doctors.index', 'icon' => 'bi-person-badge', 'active_prefix' => 'modules.admission-inpatient.doctors'],
                    ['label_key' => 'inpatient_packages', 'route' => 'modules.admission-inpatient.packages.index', 'icon' => 'bi-box-seam', 'active_prefix' => 'modules.admission-inpatient.packages', 'admin_only' => true],
                    ['label_key' => 'inpatient_package_catalog', 'route' => 'modules.admission-inpatient.package-catalog', 'icon' => 'bi-collection', 'active_prefix' => 'modules.admission-inpatient.package-catalog'],
                    ['label_key' => 'inpatient_report9', 'route' => 'modules.admission-inpatient.report9.index', 'icon' => 'bi-clipboard-data', 'active_prefix' => 'modules.admission-inpatient.report9', 'branch_ids' => [9]],
                    ['label_key' => 'inpatient_employee_report9', 'route' => 'modules.admission-inpatient.employee-report9.index', 'icon' => 'bi-people', 'active_prefix' => 'modules.admission-inpatient.employee-report9', 'branch_ids' => [9]],
                    ['label_key' => 'inpatient_nationalities', 'route' => 'modules.admission-inpatient.reference.index', 'route_params' => ['type' => 'nationalities'], 'icon' => 'bi-globe2', 'admin_only' => true],
                    ['label_key' => 'inpatient_statuses', 'route' => 'modules.admission-inpatient.reference.index', 'route_params' => ['type' => 'statuses'], 'icon' => 'bi-list-check', 'admin_only' => true],
                    ['label_key' => 'inpatient_rooms', 'route' => 'modules.admission-inpatient.reference.index', 'route_params' => ['type' => 'rooms'], 'icon' => 'bi-door-open', 'admin_only' => true],
                    ['label_key' => 'inpatient_service_prices', 'route' => 'modules.admission-inpatient.reference.index', 'route_params' => ['type' => 'service-prices'], 'icon' => 'bi-tags', 'admin_only' => true],
                    ['label_key' => 'inpatient_room_types', 'route' => 'modules.admission-inpatient.reference.index', 'route_params' => ['type' => 'room-types'], 'icon' => 'bi-grid-3x3-gap', 'admin_only' => true],
                    ['label_key' => 'inpatient_booking_periods', 'route' => 'modules.admission-inpatient.reference.index', 'route_params' => ['type' => 'booking-periods'], 'icon' => 'bi-clock-history', 'admin_only' => true],
                    ['label_key' => 'inpatient_hospitalization_places', 'route' => 'modules.admission-inpatient.reference.index', 'route_params' => ['type' => 'hospitalization-places'], 'icon' => 'bi-geo-alt', 'admin_only' => true],
                    ['label_key' => 'inpatient_approval_statuses', 'route' => 'modules.admission-inpatient.reference.index', 'route_params' => ['type' => 'medical-approval-statuses'], 'icon' => 'bi-check2-square'],
                    ['label_key' => 'inpatient_approval_reasons', 'route' => 'modules.admission-inpatient.reference.index', 'route_params' => ['type' => 'medical-approval-rejection-reasons'], 'icon' => 'bi-x-square'],
                    ['label_key' => 'inpatient_report9_sections', 'route' => 'modules.admission-inpatient.reference.index', 'route_params' => ['type' => 'rep9-sections'], 'icon' => 'bi-diagram-3', 'admin_only' => true],
                    ['label_key' => 'inpatient_report9_notices', 'route' => 'modules.admission-inpatient.reference.index', 'route_params' => ['type' => 'rep9-notices'], 'icon' => 'bi-chat-left-text', 'admin_only' => true],
                    ['label_key' => 'inpatient_report9_actions', 'route' => 'modules.admission-inpatient.reference.index', 'route_params' => ['type' => 'rep9-actions'], 'icon' => 'bi-lightning', 'admin_only' => true],
                    ['label_key' => 'inpatient_consent_templates', 'route' => 'modules.admission-inpatient.consent-templates.index', 'icon' => 'bi-file-earmark-text', 'active_prefix' => 'modules.admission-inpatient.consent-templates', 'branch_ids' => [1, 9, 34], 'admin_only' => true],
                    ['label_key' => 'inpatient_approval_contacts', 'route' => 'modules.admission-inpatient.contacts.index', 'route_params' => ['kind' => 'cc'], 'icon' => 'bi-people', 'active_prefix' => 'modules.admission-inpatient.contacts', 'branch_ids' => [10]],
                ],
            ],
            [
                'type' => 'group',
                'label_key' => 'corporate_communication',
                'icon' => 'bi-journal-bookmark',
                'children' => [
                    [
                        'type' => 'group',
                        'label_key' => 'licenses',
                        'icon' => 'bi-patch-check',
                        'children' => [
                            [
                                'label_key' => 'licenses_list',
                                'route' => 'modules.licenses.index',
                                'icon' => 'bi-card-list',
                                'active_route_patterns' => [
                                    'modules.licenses.index',
                                    'modules.licenses.show',
                                    'modules.licenses.edit',
                                    'modules.licenses.update',
                                    'modules.licenses.assign',
                                    'modules.licenses.undertaking*',
                                    'modules.licenses.pdf',
                                    'modules.licenses.export',
                                    'modules.licenses.attachments.*',
                                    'modules.licenses.notifications*',
                                    'modules.licenses.stage',
                                    'modules.licenses.comments.*',
                                    'modules.licenses.external-communications.*',
                                    'modules.licenses.renewal.*',
                                    'modules.licenses.payment-requests.*',
                                ],
                                'subtitle_key' => 'licenses.subtitle',
                                'permission' => 'licenses.view',
                            ],
                            [
                                'label_key' => 'licenses_create',
                                'route' => 'modules.licenses.create',
                                'icon' => 'bi-plus-circle',
                                'active_prefix' => 'modules.licenses.create',
                                'active_route_patterns' => ['modules.licenses.create'],
                                'subtitle_key' => 'licenses.create_subtitle',
                                'permission' => 'licenses_admin',
                            ],
                            [
                                'label_key' => 'licenses_dashboard',
                                'route' => 'modules.licenses.dashboard',
                                'icon' => 'bi-speedometer2',
                                'active_prefix' => 'modules.licenses.dashboard',
                                'active_route_patterns' => ['modules.licenses.dashboard'],
                                'subtitle_key' => 'licenses.dashboard.subtitle',
                                'permission' => 'licenses.view',
                            ],
                            [
                                'label_key' => 'licenses_finance',
                                'route' => 'modules.licenses.finance.index',
                                'icon' => 'bi-cash-coin',
                                'active_prefix' => 'modules.licenses.finance.',
                                'active_route_patterns' => ['modules.licenses.finance.*'],
                                'subtitle_key' => 'licenses.finance.subtitle',
                                'permission' => 'licenses_finance',
                            ],
                            [
                                'label_key' => 'licenses_settings',
                                'route' => 'modules.licenses.admin.index',
                                'icon' => 'bi-sliders',
                                'active_prefix' => 'modules.licenses.admin.',
                                'active_route_patterns' => ['modules.licenses.admin.*'],
                                'subtitle_key' => 'licenses.admin.subtitle',
                                'permission' => 'licenses_admin',
                            ],
                        ],
                    ],
                    [
                        'type' => 'group',
                        'label_key' => 'gov_accounts',
                        'icon' => 'bi-person-vcard',
                        'children' => [
                            [
                                'label_key' => 'gov_accounts_dashboard',
                                'route' => 'modules.gov-accounts.dashboard',
                                'icon' => 'bi-speedometer2',
                                'active_prefix' => 'modules.gov-accounts.dashboard',
                            ],
                            [
                                'label_key' => 'gov_accounts_list',
                                'route' => 'modules.gov-accounts.accounts.index',
                                'icon' => 'bi-person-vcard',
                                'active_prefix' => 'modules.gov-accounts.accounts.',
                            ],
                            [
                                'label_key' => 'gov_accounts_requests',
                                'route' => 'modules.gov-accounts.requests.index',
                                'icon' => 'bi-file-earmark-person',
                                'active_prefix' => 'modules.gov-accounts.requests.',
                            ],
                            [
                                'label_key' => 'gov_accounts_processing',
                                'route' => 'modules.gov-accounts.requests.index',
                                'icon' => 'bi-check2-square',
                                'active_prefix' => 'modules.gov-accounts.requests.',
                                'permission' => 'gov_accounts.process',
                            ],
                            [
                                'label_key' => 'gov_accounts_my_area',
                                'route' => 'modules.gov-accounts.my-accounts.index',
                                'icon' => 'bi-person',
                                'active_prefix' => 'modules.gov-accounts.my-accounts.',
                            ],
                            [
                                'label_key' => 'gov_accounts_hr',
                                'route' => 'modules.gov-accounts.hr.index',
                                'icon' => 'bi-people',
                                'active_prefix' => 'modules.gov-accounts.hr.',
                                'permission' => 'gov_accounts.hr',
                            ],
                            [
                                'label_key' => 'gov_accounts_notices',
                                'route' => 'modules.gov-accounts.notices.index',
                                'icon' => 'bi-calendar-event',
                                'active_prefix' => 'modules.gov-accounts.notices.',
                                'permission' => 'gov_accounts.process',
                            ],
                            [
                                'label_key' => 'gov_accounts_settings',
                                'route' => 'modules.gov-accounts.admin.index',
                                'icon' => 'bi-sliders',
                                'active_prefix' => 'modules.gov-accounts.admin.',
                                'active_route_patterns' => ['modules.gov-accounts.admin.*'],
                                'subtitle_key' => 'gov_accounts.settings_subtitle',
                                'permission' => 'gov_accounts_admin',
                            ],
                        ],
                    ],
                    [
                        'label_key' => 'government_circulars',
                        'route' => 'modules.government-circulars.index',
                        'icon' => 'bi-file-earmark-text',
                        'active_prefix' => 'modules.government-circulars.',
                        'subtitle_key' => 'government_circulars.subtitle',
                        'permission' => CorporateCommunicationPermissions::GOVERNMENT_CIRCULARS,
                    ],
                    [
                        'label_key' => 'inspection_visits',
                        'route' => 'modules.inspection-visits.index',
                        'icon' => 'bi-clipboard2-check',
                        'active_prefix' => 'modules.inspection-visits.',
                        'subtitle_key' => 'inspection_visits.subtitle',
                        'permission' => CorporateCommunicationPermissions::INSPECTION_VISITS,
                    ],
                    [
                        'label_key' => 'data_requests',
                        'route' => 'modules.data-requests.index',
                        'icon' => 'bi-database',
                        'active_prefix' => 'modules.data-requests.',
                        'subtitle_key' => 'data_requests.subtitle',
                        'permission' => CorporateCommunicationPermissions::DATA_REQUESTS,
                    ],
                    [
                        'label_key' => 'correspondence',
                        'route' => 'modules.correspondence.index',
                        'icon' => 'bi-envelope-open',
                        'active_prefix' => 'modules.correspondence.',
                        'subtitle_key' => 'correspondence.subtitle',
                        'permission' => CorporateCommunicationPermissions::CORRESPONDENCE,
                    ],
                    [
                        'label_key' => 'outgoing_correspondence',
                        'route' => 'modules.outgoing-correspondence.index',
                        'icon' => 'bi-envelope-paper',
                        'active_prefix' => 'modules.outgoing-correspondence.',
                        'subtitle_key' => 'outgoing_correspondence.subtitle',
                        'permission' => CorporateCommunicationPermissions::OUTGOING_CORRESPONDENCE,
                        'legacy_scope' => 'corporate-outgoing',
                    ],
                ],
            ],
            [
                'type' => 'group',
                'label_key' => 'employee_services',
                'icon' => 'bi-person-workspace',
                'children' => [
                    [
                        'label_key' => 'employee_services_notice_of_absence',
                        'route' => 'modules.work-absence.notifications.index',
                        'icon' => 'bi-bell',
                        'active_prefix' => 'modules.work-absence.notifications.',
                        'subtitle_key' => 'employee_services.card_descriptions.notice_of_absence',
                        'legacy_scope' => 'employee-services',
                    ],
                    [
                        'label_key' => 'employee_services_managing_absence',
                        'route' => 'modules.work-absence.dashboard',
                        'icon' => 'bi-clipboard-check',
                        'active_prefix' => 'modules.work-absence.dashboard',
                        'subtitle_key' => 'employee_services.card_descriptions.managing_absence_notices',
                        'legacy_scope' => 'employee-services',
                    ],
                    [
                        'label_key' => 'employee_services_leave_requests',
                        'route' => 'modules.leave.requests.index',
                        'icon' => 'bi-calendar-check',
                        'active_prefix' => 'modules.leave.',
                        'subtitle_key' => 'employee_leave.requests_subtitle',
                        'permission' => EmployeeLeavePermissions::VIEW,
                    ],
                    [
                        'label_key' => 'employee_services_training_management',
                        'route' => 'modules.training.management.index',
                        'icon' => 'bi-mortarboard',
                        'active_prefix' => 'modules.training.management.',
                        'subtitle_key' => 'training.subtitle',
                        'permission' => TrainingPermissions::MANAGEMENT,
                        'legacy_scope' => 'employee-services',
                    ],
                    [
                        'label_key' => 'employee_services_training_coordination',
                        'route' => 'modules.training.coordination.index',
                        'icon' => 'bi-mortarboard-fill',
                        'active_prefix' => 'modules.training.coordination.',
                        'subtitle_key' => 'training.subtitle',
                        'permission' => TrainingPermissions::COORDINATION,
                        'legacy_scope' => 'employee-services',
                    ],
                ],
            ],
            [
                'label_key' => 'complaints',
                'route' => 'modules.complaints',
                'icon' => 'bi-chat-square-text',
                'active_prefix' => 'modules.complaints',
                'subtitle_key' => 'complaints.subtitle',
                'permission' => 'complaints',
            ],
            [
                'label_key' => 'technical_failures',
                'route' => 'modules.technical-failures.index',
                'icon' => 'bi-tools',
                'active_prefix' => 'modules.technical-failures',
                'subtitle_key' => 'technical_failures.subtitle',
                'permission' => 'technical_failure_notice',
                'legacy_scope' => 'technical-failure',
            ],
            [
                'label_key' => 'publications',
                'route' => 'modules.publications.index',
                'icon' => 'bi-megaphone',
                'active_prefix' => 'modules.publications.',
                'subtitle_key' => 'publications.scope',
            ],
            [
                'label_key' => 'settings',
                'route' => 'modules.settings.index',
                'icon' => 'bi-sliders',
                'active_prefix' => 'modules.settings.',
                'subtitle_key' => 'settings.subtitle',
            ],
            [
                'label_key' => 'emergency_follow_up',
                'route' => 'modules.emergency-follow-up.index',
                'icon' => 'bi-clipboard2-pulse',
                'active_prefix' => 'modules.emergency-follow-up',
                'subtitle_key' => 'emergency_follow_up.subtitle',
                'branch_ids' => [1],
            ],
            [
                'label_key' => 'transferal',
                'route' => 'modules.transferal.home',
                'icon' => 'bi-arrow-left-right',
                'active_prefix' => 'modules.transferal.',
                'subtitle_key' => 'transferal.scope',
                'branch_ids' => [1],
            ],
            [
                'label_key' => 'admission_calculator',
                'route' => 'modules.admission-calculator.index',
                'route_params' => ['type' => 'standard'],
                'icon' => 'bi-calculator',
                'active_prefix' => 'modules.admission-calculator.',
                'subtitle_key' => 'admission_calculator.scope',
                'branch_ids' => [1],
            ],
            [
                'type' => 'group',
                'label_key' => 'employee_requests',
                'icon' => 'bi-person-lines-fill',
                'branch_ids' => [1],
                'children' => [
                    ['label_key' => 'employee_permission_requests', 'route' => 'modules.employee-requests.index', 'route_params' => ['type' => 'permission'], 'icon' => 'bi-clock', 'active_prefix' => 'modules.employee-requests.', 'branch_ids' => [1]],
                    ['label_key' => 'employee_duty_requests', 'route' => 'modules.employee-requests.index', 'route_params' => ['type' => 'duty'], 'icon' => 'bi-calendar2-week', 'active_prefix' => 'modules.employee-requests.', 'branch_ids' => [1]],
                    ['label_key' => 'employee_resignation_requests', 'route' => 'modules.employee-requests.index', 'route_params' => ['type' => 'resignation'], 'icon' => 'bi-person-dash', 'active_prefix' => 'modules.employee-requests.', 'branch_ids' => [1]],
                ],
            ],
            [
                'type' => 'group',
                'label_key' => 'cases',
                'icon' => 'bi-briefcase',
                // This is the old branch-3 "القضايا" menu.  The financial
                // claim screen is one child of the group, not a second,
                // competing top-level menu item.
                'children' => [
                    ['label_key' => 'cases_financial_claims', 'route' => 'modules.legal-claims.index', 'icon' => 'bi-cash-stack', 'active_prefix' => 'modules.legal-claims.', 'branch_ids' => [3]],
                    ['label_key' => 'cases_commercial', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'commercial_cases'], 'icon' => 'bi-briefcase-fill', 'branch_ids' => [3]],
                    ['label_key' => 'cases_labor', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'labor_cases'], 'icon' => 'bi-person-workspace', 'branch_ids' => [3]],
                    ['label_key' => 'cases_medical', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'medical_cases'], 'icon' => 'bi-heart-pulse', 'branch_ids' => [3]],
                    ['label_key' => 'cases_administrative', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'administrative_cases'], 'icon' => 'bi-building-check', 'branch_ids' => [3]],
                    ['label_key' => 'cases_executive_titles', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'executive_title'], 'icon' => 'bi-file-earmark-lock', 'branch_ids' => [3]],
                ],
            ],
            [
                'type' => 'group',
                'label_key' => 'financial_claims',
                'icon' => 'bi-cash-stack',
                'branch_ids' => [2],
                'children' => [
                    // These have the same underlying workflows as entries in
                    // "القضايا".  Keep a menu context in the URL so the
                    // sidebar's duplicate-url guard does not remove them from
                    // this separate, legacy financial-claims menu.
                    ['label_key' => 'financial_claims_cases', 'route' => 'modules.legal-claims.index', 'route_params' => ['menu' => 'financial-claims'], 'icon' => 'bi-briefcase', 'active_prefix' => 'modules.legal-claims.', 'branch_ids' => [2]],
                    ['label_key' => 'financial_claims_executive_titles', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'executive_title', 'menu' => 'financial-claims'], 'icon' => 'bi-file-earmark-lock', 'branch_ids' => [2]],
                    ['label_key' => 'financial_claims_claim_documents', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'lawsuit_complete_documents'], 'icon' => 'bi-folder-check', 'branch_ids' => [2]],
                    ['label_key' => 'financial_claims_executive_documents', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'executive_title_complete_documents'], 'icon' => 'bi-file-earmark-check', 'branch_ids' => [2]],
                    ['label_key' => 'financial_claims_payment_guarantee', 'route' => 'modules.medical-agreements.index', 'route_params' => ['variant' => 'sadq'], 'icon' => 'bi-patch-check', 'active_prefix' => 'modules.medical-agreements.', 'branch_ids' => [2], 'legacy_scope' => 'sadq', 'legacy_privilege' => 'Medical Services Provision Agreement Yaqeen'],
                    ['label_key' => 'financial_claims_payment_guarantee_archive', 'route' => 'modules.medical-agreements.index', 'route_params' => ['variant' => 'standard'], 'icon' => 'bi-archive', 'active_prefix' => 'modules.medical-agreements.', 'branch_ids' => [2], 'legacy_scope' => 'sadq', 'legacy_privilege' => 'Medical Services Provision Agreement non Yaqeen'],
                    ['label_key' => 'financial_claims_notice', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'financial_claim_notice'], 'icon' => 'bi-cash-coin', 'branch_ids' => [2]],
                    ['label_key' => 'financial_claims_approval', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'lawsuitapproval'], 'icon' => 'bi-check2-square', 'branch_ids' => [2]],
                    ['label_key' => 'financial_claims_inquiry', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'sit_rep2'], 'icon' => 'bi-question-circle', 'branch_ids' => [2]],
                    ['label_key' => 'financial_claims_legal_inquiry', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'archives'], 'icon' => 'bi-journal-text', 'branch_ids' => [2]],
                    ['label_key' => 'financial_claims_medical_report', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'rep_ss'], 'icon' => 'bi-file-medical', 'branch_ids' => [2]],
                ],
            ],
            [
                'type' => 'group',
                'label_key' => 'department_reports',
                'icon' => 'bi-bar-chart-line',
                'children' => [
                    [
                        'label_key' => 'collection_report',
                        'route' => 'modules.department-reports.index',
                        'route_params' => ['department' => 'collection'],
                        'icon' => 'bi-cash-stack',
                        'active_prefix' => 'modules.department-reports.',
                    ],
                    [
                        'label_key' => 'legal_report',
                        'route' => 'modules.department-reports.index',
                        'route_params' => ['department' => 'legal'],
                        'icon' => 'bi-briefcase',
                        'active_prefix' => 'modules.department-reports.',
                    ],
                ],
            ],
            [
                'type' => 'group',
                'label_key' => 'medical_appointments',
                'icon' => 'bi-heart-pulse',
                'branch_ids' => MedicalAppointmentScope::BRANCH_IDS,
                'company_ids' => MedicalAppointmentScope::COMPANY_IDS,
                'children' => [
                    [
                        'label_key' => 'medical_appointment_requests',
                        'route' => 'modules.medical-appointments.index',
                        'icon' => 'bi-calendar-plus',
                        'active_prefix' => 'modules.medical-appointments.',
                        'subtitle_key' => 'medical_appointments.subtitle',
                        'branch_ids' => MedicalAppointmentScope::BRANCH_IDS,
                        'company_ids' => MedicalAppointmentScope::COMPANY_IDS,
                    ],
                    [
                        'label_key' => 'medical_appointment_clinics',
                        // شاشة مستقلة تكافئ clinicians_view.php داخل تصميم المشروع الجديد.
                        // Link directly to the new screen. The legacy alias
                        // remains available for old bookmarks, but using it
                        // in the sidebar made the SPA transition resolve a
                        // relative .php URL on the production Nginx setup.
                        'route' => 'modules.clinics-directory.index',
                        'icon' => 'bi-building',
                        'active_prefixes' => ['legacy.clinicians-view', 'modules.clinics-directory.'],
                        'subtitle_key' => 'service_locations.subtitle',
                        'branch_ids' => MedicalAppointmentScope::BRANCH_IDS,
                        'company_ids' => MedicalAppointmentScope::COMPANY_IDS,
                    ],
                ],
            ],
            [
                'type' => 'group',
                'label_key' => 'legacy_emergency_reception',
                'icon' => 'bi-hospital',
                'branch_ids' => [1, 2],
                'user_levels' => [1, 2, 4],
                'children' => [
                    ['label_key' => 'emergency_cases_process', 'route' => 'modules.emergency-reception.guide', 'route_params' => ['guide' => 'emergency-cases'], 'icon' => 'bi-journal-medical', 'branch_ids' => [1], 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'emergency_reception_mechanism', 'route' => 'modules.emergency-reception.guide', 'route_params' => ['guide' => 'emergency-reception'], 'icon' => 'bi-signpost-split', 'branch_ids' => [1], 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'health_service_purchase', 'route' => 'modules.health-service-purchase.index', 'icon' => 'bi-person-vcard', 'active_prefix' => 'modules.health-service-purchase.', 'branch_ids' => [1, 2], 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'receiving_corpse', 'route' => 'modules.emergency-reception.index', 'route_params' => ['type' => 'corpse'], 'icon' => 'bi-file-earmark-medical', 'branch_ids' => [1], 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'claiming_against_others', 'route' => 'modules.emergency-reception.index', 'route_params' => ['type' => 'claim'], 'icon' => 'bi-file-earmark-check', 'branch_ids' => [1], 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'unidentified_case', 'route' => 'modules.emergency-reception.index', 'route_params' => ['type' => 'unidentified'], 'icon' => 'bi-person-exclamation', 'branch_ids' => [1], 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'escape_report', 'route' => 'modules.emergency-reception.index', 'route_params' => ['type' => 'escape'], 'icon' => 'bi-door-open', 'branch_ids' => [1], 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'incident_report', 'route' => 'modules.emergency-reception.index', 'route_params' => ['type' => 'incident'], 'icon' => 'bi-exclamation-triangle', 'branch_ids' => [1], 'user_levels' => [1, 2, 4]],
                ],
            ],
            [
                'type' => 'group',
                'label_key' => 'legacy_medical_referrals',
                'icon' => 'bi-heart-pulse',
                'branch_ids' => [1],
                'user_levels' => [1, 2, 4],
                'children' => [
                    ['label_key' => 'pulse_status', 'route' => 'modules.medical-referrals.index', 'route_params' => ['type' => 'pulse-status'], 'icon' => 'bi-activity', 'branch_ids' => [1], 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'bed_reservation', 'route' => 'modules.medical-referrals.index', 'route_params' => ['type' => 'bed-reservation'], 'icon' => 'bi-hospital', 'branch_ids' => [1], 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'accept_referral', 'route' => 'modules.medical-referrals.index', 'route_params' => ['type' => 'accept-referral'], 'icon' => 'bi-check2-circle', 'branch_ids' => [1], 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'referral_apology', 'route' => 'modules.medical-referrals.index', 'route_params' => ['type' => 'referral-apology'], 'icon' => 'bi-x-circle', 'branch_ids' => [1], 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'crisis_management', 'route' => 'modules.medical-referrals.index', 'route_params' => ['type' => 'crisis-management'], 'icon' => 'bi-shield-exclamation', 'branch_ids' => [1], 'user_levels' => [1, 2, 4]],
                    ['label_key' => 'red_crescent', 'route' => 'modules.medical-referrals.index', 'route_params' => ['type' => 'red-crescent'], 'icon' => 'bi-truck-front', 'branch_ids' => [1], 'user_levels' => [1, 2, 4]],
                ],
            ],
            [
                'type' => 'group',
                'label_key' => 'legacy_memos',
                'icon' => 'bi-sticky',
                'user_levels' => [0, 1, 2, 4],
                'children' => [
                    ['label_key' => 'outgoing_memos', 'route' => 'modules.legacy-office.memos.index', 'icon' => 'bi-send', 'active_prefix' => 'modules.legacy-office.memos.', 'user_levels' => [0, 1, 2, 4]],
                    ['label_key' => 'received_memos', 'route' => 'modules.legacy-office.memos.received', 'icon' => 'bi-inbox', 'active_prefix' => 'modules.legacy-office.memos.', 'user_levels' => [0, 1, 2, 4]],
                    ['label_key' => 'coverage_memos', 'route' => 'modules.legacy-office.coverage.index', 'icon' => 'bi-file-earmark-medical', 'active_prefix' => 'modules.legacy-office.coverage.', 'branch_ids' => [1, 2, 8], 'user_levels' => [0, 1, 2, 4]],
                ],
            ],
            [
                'type' => 'group',
                'label_key' => 'legacy_sidebar_pages',
                'icon' => 'bi-arrow-repeat',
                'children' => [
                    ['label_key' => 'legacy_sidebar_adm_country', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'adm_country'], 'icon' => 'bi-globe2', 'admin_only' => true],
                    ['label_key' => 'legacy_sidebar_archives', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'archives'], 'icon' => 'bi-archive', 'excluded_branch_ids' => [2]],
                    ['label_key' => 'legacy_sidebar_birth_notification', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'birth_notification'], 'icon' => 'bi-person-heart'],
                    ['label_key' => 'legacy_sidebar_branches_emails', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'branches_emails'], 'icon' => 'bi-envelope'],
                    ['label_key' => 'legacy_sidebar_central_follow_up', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'central_follow_up'], 'icon' => 'bi-telephone-forward'],
                    ['label_key' => 'legacy_sidebar_central_ext', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'central_ext'], 'icon' => 'bi-telephone'],
                    ['label_key' => 'legacy_sidebar_centralsections', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'centralsections'], 'icon' => 'bi-diagram-2'],
                    ['label_key' => 'legacy_sidebar_city', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'city'], 'icon' => 'bi-buildings', 'admin_only' => true],
                    ['label_key' => 'legacy_sidebar_emergency_new_call', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'emergency_new_call'], 'icon' => 'bi-broadcast-pin'],
                    ['label_key' => 'legacy_sidebar_executive_title_complete_documents', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'executive_title_complete_documents'], 'icon' => 'bi-file-earmark-check', 'excluded_branch_ids' => [2]],
                    ['label_key' => 'legacy_sidebar_financial_claim_notice', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'financial_claim_notice'], 'icon' => 'bi-cash-coin', 'excluded_branch_ids' => [2]],
                    ['label_key' => 'legacy_sidebar_info', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'info'], 'icon' => 'bi-info-circle'],
                    ['label_key' => 'legacy_sidebar_lawsuit_complete_documents', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'lawsuit_complete_documents'], 'icon' => 'bi-folder-check', 'excluded_branch_ids' => [2]],
                    ['label_key' => 'legacy_sidebar_lawsuit_users_mobile', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'lawsuit_users_mobile'], 'icon' => 'bi-phone'],
                    ['label_key' => 'legacy_sidebar_lawsuitapproval', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'lawsuitapproval'], 'icon' => 'bi-check2-square', 'excluded_branch_ids' => [2]],
                    ['label_key' => 'legacy_sidebar_medica_report', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'medica_report'], 'icon' => 'bi-file-medical'],
                    ['label_key' => 'legacy_sidebar_onlinetody', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'onlinetody'], 'icon' => 'bi-calendar2-check', 'admin_only' => true],
                    ['label_key' => 'legacy_sidebar_psychosocial_assessment_all', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'psychosocial_assessment_all'], 'icon' => 'bi-people-fill'],
                    ['label_key' => 'legacy_sidebar_sanad_reg', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'sanad_reg'], 'icon' => 'bi-journal-plus', 'admin_only' => true],
                    ['label_key' => 'legacy_sidebar_sanad_track1', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'sanad_track1'], 'icon' => 'bi-journal-check', 'admin_only' => true],
                    ['label_key' => 'legacy_sidebar_shift_schedule', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'shift_schedule'], 'icon' => 'bi-calendar3'],
                    ['label_key' => 'legacy_sidebar_sms', 'route' => 'modules.legacy-sidebar.index', 'route_params' => ['page' => 'sms'], 'icon' => 'bi-chat-dots'],
                ],
            ],
            [
                'type' => 'group',
                'label_key' => 'system_administration',
                'icon' => 'bi-shield-lock',
                'admin_only' => true,
                'children' => [
                    [
                        'label_key' => 'system_admin_overview',
                        'route' => 'modules.system-admin.dashboard',
                        'icon' => 'bi-speedometer2',
                        'active_prefix' => 'modules.system-admin.dashboard',
                        'subtitle_key' => 'system_administration.dashboard_subtitle',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_services',
                        'route' => 'modules.system-admin.packages.index',
                        'icon' => 'bi-hospital',
                        'active_prefix' => 'modules.system-admin.packages.',
                        'subtitle_key' => 'system_administration.packages_subtitle',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_doctors',
                        'route' => 'modules.doctors-admin.dashboard',
                        'icon' => 'bi-gear-wide-connected',
                        'active_prefix' => 'modules.doctors-admin.',
                        'subtitle_key' => 'doctors_directory_admin.dashboard_subtitle',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_emergency_reports',
                        'route' => 'modules.emergency-reports.index',
                        'icon' => 'bi-graph-up-arrow',
                        'active_prefix' => 'modules.emergency-reports',
                        'subtitle_key' => 'emergency_reports.subtitle',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_complaint_references',
                        'route' => 'modules.system-admin.reference.index',
                        'route_params' => ['type' => 'complaint-statuses'],
                        'icon' => 'bi-chat-square-text',
                        'active_prefix' => 'modules.system-admin.reference.',
                        'subtitle_key' => 'system_administration.reference.scope',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_complaint_closing_reasons',
                        'route' => 'modules.system-admin.reference.index',
                        'route_params' => ['type' => 'complaint-closing-reasons'],
                        'icon' => 'bi-x-circle',
                        'active_prefix' => 'modules.system-admin.reference.',
                        'subtitle_key' => 'system_administration.reference.scope',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_complaint_letter_receivers',
                        'route' => 'modules.system-admin.reference.index',
                        'route_params' => ['type' => 'complaint-letter-receivers'],
                        'icon' => 'bi-envelope-paper',
                        'active_prefix' => 'modules.system-admin.reference.',
                        'subtitle_key' => 'system_administration.reference.scope',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_terminology',
                        'route' => 'modules.system-admin.reference.index',
                        'route_params' => ['type' => 'medical-terminology'],
                        'icon' => 'bi-journal-medical',
                        'active_prefix' => 'modules.system-admin.reference.',
                        'subtitle_key' => 'system_administration.reference.scope',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_service_codes',
                        'route' => 'modules.system-admin.reference.index',
                        'route_params' => ['type' => 'service-codes'],
                        'icon' => 'bi-upc-scan',
                        'active_prefix' => 'modules.system-admin.reference.',
                        'subtitle_key' => 'system_administration.reference.scope',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_post_types',
                        'route' => 'modules.system-admin.reference.index',
                        'route_params' => ['type' => 'post-types'],
                        'icon' => 'bi-file-earmark-text',
                        'active_prefix' => 'modules.system-admin.reference.',
                        'subtitle_key' => 'system_administration.reference.scope',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_job_titles',
                        'route' => 'modules.system-admin.reference.index',
                        'route_params' => ['type' => 'job-titles'],
                        'icon' => 'bi-person-badge',
                        'active_prefix' => 'modules.system-admin.reference.',
                        'subtitle_key' => 'system_administration.reference.scope',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_governmental_services',
                        'route' => 'modules.system-admin.reference.index',
                        'route_params' => ['type' => 'governmental-services'],
                        'icon' => 'bi-building-check',
                        'active_prefix' => 'modules.system-admin.reference.',
                        'subtitle_key' => 'system_administration.reference.scope',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_companies',
                        'route' => 'modules.system-admin.reference.index',
                        'route_params' => ['type' => 'companies'],
                        'icon' => 'bi-buildings',
                        'active_prefix' => 'modules.system-admin.reference.',
                        'subtitle_key' => 'system_administration.reference.scope',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_branches',
                        'route' => 'modules.system-admin.reference.index',
                        'route_params' => ['type' => 'branches'],
                        'icon' => 'bi-diagram-3',
                        'active_prefix' => 'modules.system-admin.reference.',
                        'subtitle_key' => 'system_administration.reference.scope',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_departments',
                        'route' => 'modules.system-admin.reference.index',
                        'route_params' => ['type' => 'departments'],
                        'icon' => 'bi-diagram-2',
                        'active_prefix' => 'modules.system-admin.reference.',
                        'subtitle_key' => 'system_administration.reference.scope',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_needs',
                        'route' => 'modules.system-admin.reference.index',
                        'route_params' => ['type' => 'needs'],
                        'icon' => 'bi-list-check',
                        'active_prefix' => 'modules.system-admin.reference.',
                        'subtitle_key' => 'system_administration.reference.scope',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_work_areas',
                        'route' => 'modules.system-admin.reference.index',
                        'route_params' => ['type' => 'work-areas'],
                        'icon' => 'bi-geo-alt',
                        'active_prefix' => 'modules.system-admin.reference.',
                        'subtitle_key' => 'system_administration.reference.scope',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_inquiry_types',
                        'route' => 'modules.system-admin.reference.index',
                        'route_params' => ['type' => 'inquiries'],
                        'icon' => 'bi-question-circle',
                        'active_prefix' => 'modules.system-admin.reference.',
                        'subtitle_key' => 'system_administration.reference.scope',
                        'admin_only' => true,
                    ],
                    [
                        'label_key' => 'system_admin_service_types',
                        'route' => 'modules.system-admin.reference.index',
                        'route_params' => ['type' => 'service-types'],
                        'icon' => 'bi-tags',
                        'active_prefix' => 'modules.system-admin.reference.',
                        'subtitle_key' => 'system_administration.reference.scope',
                        'admin_only' => true,
                    ],
                ],
            ],
            [
                'label_key' => 'system_admin_users',
                'route' => 'modules.system-admin.users.index',
                'icon' => 'bi-people',
                'active_prefix' => 'modules.system-admin.users.',
                'subtitle_key' => 'system_administration.users.scope_notice',
                'permission_admin_only' => true,
            ],
        ],
    ],

    'notifications' => [
        'enabled' => false,
        'items' => [],
    ],

    'cc_notifications' => [
        'enabled' => (bool) env('HM_CC_NOTIFICATIONS_ENABLED', false),
        'mail' => (bool) env('HM_CC_NOTIFICATIONS_MAIL', true),
        'sms' => (bool) env('HM_CC_NOTIFICATIONS_SMS', false),
        // Daily department reminders (inspection visits + data requests).
        'reminders' => (bool) env('HM_CC_REMINDERS_ENABLED', true),
        'reminders_at' => env('HM_CC_REMINDERS_AT', '07:00'),
        'timezone' => env('HM_CC_REMINDERS_TIMEZONE', 'Asia/Riyadh'),
    ],

    /*
    | SMS gateway used by Corporate Communication (and reusable elsewhere).
    | provider: log | mshastra | synapse
    | Use "log" locally; switch to mshastra/synapse with credentials in production.
    */
    'sms' => [
        'provider' => env('HM_SMS_PROVIDER', 'log'),
        'sender' => env('HM_SMS_SENDER', 'ALHAMMADI'),
        'mshastra' => [
            'user' => env('HM_SMS_MSHASTRA_USER', ''),
            'password' => env('HM_SMS_MSHASTRA_PASSWORD', ''),
        ],
        'synapse' => [
            'url' => env('HM_SMS_SYNAPSE_URL', 'https://api.synapse4sa.com/v1/multichannel/messages/sendsms'),
            'user' => env('HM_SMS_SYNAPSE_USER', ''),
            'password' => env('HM_SMS_SYNAPSE_PASSWORD', ''),
        ],
    ],

    'doctors_directory' => [
        'per_page' => (int) env('HM_DOCTORS_DIRECTORY_PER_PAGE', 12),
        'photos_path' => env('HM_CLINICIANS_PHOTOS_PATH', '/files'),
        // Main outpatient hospital branches shown on the speciality overview
        // (matches legacy clinic_details.php — Nuzha + Suwaidi).
        'outpatient_branch_ids' => [1, 3],
        'branch_images' => [
            1 => 'النزهة.jpeg',
            3 => 'السويدي.jpeg',
        ],
        // Doctor codes assigned primarily to Suwaidi — strip erroneous Nuzha rows after cleanup.
        'suwaidi_primary_doctor_codes' => [
            '292', '19226', '18754', '17609',
            '90321', '90322', '90323',
        ],
    ],

    'system_administration' => [
        'per_page' => (int) env('HM_SYSTEM_ADMIN_PER_PAGE', 15),
        'cards' => [
            [
                'label_key' => 'packages',
                'route' => 'modules.system-admin.packages.index',
                'icon' => 'bi-hospital',
            ],
            [
                'label_key' => 'doctors_directory',
                'route' => 'modules.doctors-admin.dashboard',
                'icon' => 'bi-gear-wide-connected',
            ],
            ['label_key' => 'job_titles', 'route' => 'modules.system-admin.reference.index', 'route_params' => ['type' => 'job-titles'], 'icon' => 'bi-person-badge'],
            ['label_key' => 'governmental_services', 'route' => 'modules.system-admin.reference.index', 'route_params' => ['type' => 'governmental-services'], 'icon' => 'bi-building-check'],
            ['label_key' => 'companies', 'route' => 'modules.system-admin.reference.index', 'route_params' => ['type' => 'companies'], 'icon' => 'bi-buildings'],
            ['label_key' => 'branches', 'route' => 'modules.system-admin.reference.index', 'route_params' => ['type' => 'branches'], 'icon' => 'bi-diagram-3'],
            ['label_key' => 'departments', 'route' => 'modules.system-admin.reference.index', 'route_params' => ['type' => 'departments'], 'icon' => 'bi-diagram-2'],
            ['label_key' => 'needs', 'route' => 'modules.system-admin.reference.index', 'route_params' => ['type' => 'needs'], 'icon' => 'bi-list-check'],
            ['label_key' => 'work_areas', 'route' => 'modules.system-admin.reference.index', 'route_params' => ['type' => 'work-areas'], 'icon' => 'bi-geo-alt'],
            ['label_key' => 'inquiry_types', 'route' => 'modules.system-admin.reference.index', 'route_params' => ['type' => 'inquiries'], 'icon' => 'bi-question-circle'],
        ],
    ],

    'doctors_directory_admin' => [
        'per_page' => (int) env('HM_DOCTORS_DIRECTORY_ADMIN_PER_PAGE', 15),
        'cards' => [
            [
                'label_key' => 'specialities',
                'route' => 'modules.doctors-admin.specialities.index',
                'icon' => 'bi-diagram-3',
            ],
            [
                'label_key' => 'departments',
                'route' => 'modules.doctors-admin.departments.index',
                'icon' => 'bi-building',
            ],
            [
                'label_key' => 'doctors',
                'route' => 'modules.doctors-admin.doctors.index',
                'icon' => 'bi-person-vcard',
            ],
        ],
    ],

    'employee_leave' => [
        'per_page' => (int) env('HM_EMPLOYEE_LEAVE_PER_PAGE', 15),
        // Reserved ID for "Other" — custom text stored in emp_vacations.other_contacts
        'other_leave_type_id' => 99,
        'approval_status_ids' => [
            'approved' => 1,
            'rejected' => 2,
            'partial' => 3,
            'pending' => 4,
        ],
        'leave_types' => [
            1 => ['en' => 'Annual leave', 'ar' => 'إجازة سنوية'],
            2 => ['en' => 'Sick leave', 'ar' => 'إجازة مرضية'],
            3 => ['en' => 'Emergency leave', 'ar' => 'إجازة طارئة'],
            4 => ['en' => 'Unpaid leave', 'ar' => 'إجازة بدون راتب'],
            6 => ['en' => 'Hajj leave', 'ar' => 'إجازة حج'],
            8 => ['en' => 'Marriage leave', 'ar' => 'إجازة زواج'],
            12 => ['en' => 'Maternity leave', 'ar' => 'إجازة أمومة'],
            13 => ['en' => 'Bereavement leave', 'ar' => 'إجازة وفاة'],
            99 => ['en' => 'Other', 'ar' => 'أخرى'],
        ],
    ],

    'complaints' => [
        'per_page' => (int) env('HM_COMPLAINTS_PER_PAGE', 15),
        'dashboard_stats' => [
            'active' => [0, 1, 2, 3, 4],
            'processed' => 5,
            'closed' => 6,
        ],
        'types' => [
            1 => ['en' => 'Internal complaint', 'ar' => 'شكوى داخلية'],
            2 => ['en' => 'External complaint', 'ar' => 'شكوى خارجية'],
        ],
        'priorities' => [
            0 => ['en' => 'Low', 'ar' => 'منخفضة'],
            1 => ['en' => 'High', 'ar' => 'عالية'],
        ],
    ],

    'corporate_communication' => [
        'cards' => [
            [
                'label_key' => 'government_circulars',
                'description_key' => 'government_circulars.subtitle',
                'route' => 'modules.government-circulars.index',
                'icon' => 'bi-file-earmark-text',
            ],
            [
                'label_key' => 'inspection_visits',
                'description_key' => 'inspection_visits.subtitle',
                'route' => 'modules.inspection-visits.index',
                'icon' => 'bi-clipboard2-check',
            ],
            [
                'label_key' => 'data_requests',
                'description_key' => 'data_requests.subtitle',
                'route' => 'modules.data-requests.index',
                'icon' => 'bi-database',
            ],
            [
                'label_key' => 'correspondence',
                'description_key' => 'correspondence.subtitle',
                'route' => 'modules.correspondence.index',
                'icon' => 'bi-envelope-open',
            ],
            [
                'label_key' => 'outgoing_correspondence',
                'description_key' => 'outgoing_correspondence.subtitle',
                'route' => 'modules.outgoing-correspondence.index',
                'icon' => 'bi-envelope-paper',
            ],
        ],
    ],

    'gov_accounts' => [
        'notifications' => [
            'mail' => (bool) env('HM_GOV_ACCOUNTS_MAIL_ENABLED', false),
            'sms' => false,
        ],
        'employee_status' => [
            'enabled' => (bool) env('HM_GOV_ACCOUNTS_EMPLOYEE_STATUS_ENABLED', false),
            'scheduler_at' => env('HM_GOV_ACCOUNTS_EMPLOYEE_STATUS_AT', '07:30'),
        ],
    ],

    'government_circulars' => [
        'per_page' => (int) env('HM_GOVERNMENT_CIRCULARS_PER_PAGE', 15),
    ],

    'inspection_visits' => [
        'per_page' => (int) env('HM_INSPECTION_VISITS_PER_PAGE', 15),
    ],

    'data_requests' => [
        'per_page' => (int) env('HM_DATA_REQUESTS_PER_PAGE', 15),
    ],

    'correspondence' => [
        'per_page' => (int) env('HM_CORRESPONDENCE_PER_PAGE', 15),
    ],

    'outgoing_correspondence' => [
        'per_page' => (int) env('HM_OUTGOING_CORRESPONDENCE_PER_PAGE', 15),
    ],

    'licenses' => [
        'per_page' => max(5, (int) env('HM_LICENSES_PER_PAGE', 15)),
        'alert_days' => [
            max(1, (int) env('HM_LICENSES_YELLOW_DAYS', 90)),
            max(1, (int) env('HM_LICENSES_REMINDER_DAYS', 60)),
            max(1, (int) env('HM_LICENSES_RED_DAYS', 30)),
        ],
        'undertaking_escalation_days' => max(1, (int) env('HM_LICENSES_UNDERTAKING_DAYS', 3)),
        'expired_reescalate_days' => max(1, (int) env('HM_LICENSES_EXPIRED_REESCALATE_DAYS', 7)),
        'scheduler_at' => env('HM_LICENSES_SCHEDULER_AT', '07:15'),
        'timezone' => env('HM_LICENSES_TIMEZONE', 'Asia/Riyadh'),
        'notifications' => [
            'enabled' => (bool) env('HM_LICENSES_NOTIFICATIONS_ENABLED', true),
            'mail' => (bool) env('HM_LICENSES_MAIL_ENABLED', true),
            'sms' => (bool) env('HM_LICENSES_SMS_ENABLED', false),
        ],
    ],

    'inquiries' => [
        'per_page' => (int) env('HM_INQUIRIES_PER_PAGE', 15),
        'new_status_ids' => [999999, 1, 0],
        'forward_status_id' => 999999,
        'update_status_ids' => [3, 4, 5, 6, 999999],
        'stat_statuses' => [
            'new' => [999999, 1, 0],
            'in_progress' => [3],
            'contacted' => [4],
            'contacted_not_booked' => [5],
            'completed' => [6],
        ],
        // Branch id => destination department (branch) ids for incoming list when scoped.
        'branch_incoming_sections' => [
            5 => [1],
            6 => [1],
        ],
    ],

    'employee_services' => [
        'cards' => [
            [
                'label_key' => 'notice_of_absence',
                'route' => 'modules.work-absence.notifications.index',
                'icon' => 'bi-bell',
            ],
            [
                'label_key' => 'managing_absence_notices',
                'route' => 'modules.work-absence.dashboard',
                'icon' => 'bi-clipboard-check',
            ],
        ],
    ],

    'work_absence_notification' => [
        'per_page' => (int) env('HM_WORK_ABSENCE_NOTIFICATION_PER_PAGE', 15),
        'permissions' => [
            'view' => 'work_absence_notification.view',
            'process' => 'work_absence_notification.process',
            'activate' => 'work_absence_notification.activate',
            'export' => 'work_absence_notification.export',
        ],
    ],

    'hospital_services' => [
        'per_page' => (int) env('HM_HOSPITAL_SERVICES_PER_PAGE', 15),
        'attachments_path' => env('HM_SERVICE_ATTACHMENTS_PATH', '/files'),
        'room_sections' => [7],
        // Legacy top-nav "الخدمات" dropdown order and labels.
        'section_nav_order' => [1, 2, 3, 4, 6, 11, 12],
        'section_nav_labels' => [
            1 => ['ar' => 'العيادات الخارجية', 'en' => 'Outpatient Clinics'],
            2 => ['ar' => 'الأشعة', 'en' => 'Radiology'],
            3 => ['ar' => 'المختبر', 'en' => 'Laboratory'],
            4 => ['ar' => 'العلاج الطبيعي', 'en' => 'Physiotherapy'],
            6 => ['ar' => 'التنويم', 'en' => 'Inpatient'],
            7 => ['ar' => 'الغرف و الأجنحة', 'en' => 'Rooms and Suites'],
            8 => ['ar' => 'وحدة العقم و الإنجاب', 'en' => 'Infertility and Reproduction Unit'],
            9 => ['ar' => 'وحدة المناظير', 'en' => 'Endoscopy Unit'],
            10 => ['ar' => 'وحدة غسيل الكلى', 'en' => 'Dialysis Unit'],
            11 => ['ar' => 'الشراكات و الخصومات', 'en' => 'Partnerships and Discounts'],
            12 => ['ar' => 'المراكز المتعاقدة الطبية', 'en' => 'Contracted Medical Centers'],
        ],
        'section_nav_children' => [
            6 => [7, 8, 9, 10],
        ],
        // Legacy service_details.php?id=6 (التنويم) — parent only; sub-sections use their own ids.
        'section_content_aliases' => [
            6 => 7,
        ],
        'sections' => [
            'outpatient' => 1,
            'lab' => 3,
            'radiology' => 2,
            'agreements' => 11,
        ],
        'cards' => [
            [
                'label_key' => 'outpatient',
                'route' => 'modules.services.sections.show',
                'section_id' => 1,
                'icon' => 'bi-clipboard2-pulse',
            ],
            [
                'label_key' => 'lab',
                'route' => 'modules.services.sections.show',
                'section_id' => 3,
                'icon' => 'bi-droplet',
            ],
            [
                'label_key' => 'radiology',
                'route' => 'modules.services.sections.show',
                'section_id' => 2,
                'icon' => 'bi-radioactive',
            ],
            [
                'label_key' => 'private_rooms',
                'route' => 'modules.services.rooms.index',
                'icon' => 'bi-door-closed',
            ],
            [
                'label_key' => 'agreements',
                'route' => 'modules.services.sections.show',
                'section_id' => 11,
                'icon' => 'bi-percent',
            ],
        ],
    ],

    'service_locations' => [
        // Ordered department lists matching the legacy outpatient_clinics_sections.php pages.
        // Used when the local DB does not link every speciality directly to outpatient_clinics_id.
        'opd_departments' => [
            1 => [
                ['speciality_id' => 7],
                ['speciality_id' => 1],
                ['speciality_id' => 20],
                ['speciality_id' => 31],
                ['speciality_id' => 39],
                ['speciality_id' => 16],
                ['speciality_id' => 27],
                ['speciality_id' => 12],
                ['label_key' => 'breast_feeding_department'],
                ['speciality_id' => 11],
                ['speciality_id' => 8],
                ['speciality_id' => 19],
                ['speciality_id' => 60],
                ['speciality_id' => 58],
                ['speciality_id' => 35],
            ],
            2 => [
                ['speciality_id' => 7],
                ['speciality_id' => 11],
                ['speciality_id' => 60],
                ['speciality_id' => 9],
                ['speciality_id' => 16],
                ['speciality_id' => 65],
                ['speciality_id' => 39],
            ],
            3 => [
                ['speciality_id' => 1],
                ['speciality_id' => 4],
                ['speciality_id' => 45],
                ['speciality_id' => 6],
                ['speciality_id' => 8],
                ['speciality_id' => 40],
            ],
            4 => [
                ['speciality_id' => 14],
                ['speciality_id' => 15],
                ['speciality_id' => 17],
            ],
            5 => [
                ['speciality_id' => 20],
                ['speciality_id' => 25],
                ['speciality_id' => 23],
                ['speciality_id' => 42],
                ['speciality_id' => 22],
                ['speciality_id' => 30],
                ['speciality_id' => 24],
                ['speciality_id' => 36],
                ['speciality_id' => 21],
                ['speciality_id' => 31],
            ],
            6 => [
                ['speciality_id' => 12],
                ['speciality_id' => 9],
                ['speciality_id' => 28],
                ['speciality_id' => 8],
                ['speciality_id' => 27],
                ['speciality_id' => 13],
                ['speciality_id' => 26],
                ['speciality_id' => 11],
                ['speciality_id' => 1],
                ['speciality_id' => 2],
                ['speciality_id' => 3],
                ['speciality_id' => 4],
                ['speciality_id' => 7],
            ],
        ],
    ],

];
