@extends('layouts.app')
@section('title',__('licenses.admin.escalation_groups'))
@section('sidebar_heading',__('licenses.title'))
@push('styles')<link href="{{ asset('css/hm-licenses.css') }}?v={{ filemtime(public_path('css/hm-licenses.css')) }}" rel="stylesheet">@endpush
@section('content')
@php $url=static fn($n,$p=[])=>\Illuminate\Support\Facades\Route::has($n)?route($n,$p):'#';$members=$group->members ?? collect();$usersList=$users ?? collect();$userName=static function($u){if(!$u)return '—';if(method_exists($u,'displayName'))return $u->displayName();return $u->hr_name ?? $u->name ?? '—';}; @endphp
<div class="hm-licenses">@include('licenses.partials.page-header',['title'=>__('licenses.admin.edit',['item'=>__('licenses.admin.escalation_groups')]),'subtitle'=>__('licenses.admin.subtitle'),'icon'=>'bi-pencil-square','actions'=>new \Illuminate\Support\HtmlString('<a class="lic-btn" href="'.e($url('modules.licenses.admin.escalation-groups.index')).'">'.e(__('licenses.back')).'</a>')])@include('licenses.partials.feedback')
<div class="lic-two-column"><div class="lic-stack"><section class="lic-panel"><form method="POST" action="{{ $url('modules.licenses.admin.escalation-groups.update',$group->getRouteKey()) }}">@csrf @method('PUT') @include('licenses.admin.escalation-groups._form',['group'=>$group])<div class="lic-form-actions"><button class="lic-btn lic-btn--primary" type="submit">{{ __('licenses.save_changes') }}</button><a class="lic-btn" href="{{ $url('modules.licenses.admin.escalation-groups.index') }}">{{ __('licenses.cancel') }}</a></div></form></section>
<section class="lic-panel"><h2 class="lic-panel__title"><i class="bi bi-person-lines-fill"></i>{{ __('licenses.admin.members') }}</h2>@forelse($members as $member)@php $memberUser=$member->user ?? null; @endphp<article class="lic-member"><strong>{{ $userName($memberUser) }}</strong><span class="lic-sensitive">{{ data_get($memberUser,'hr_email_address') ?: data_get($memberUser,'email') ?: '—' }}</span><span class="lic-sensitive">{{ data_get($memberUser,'mobile') ?: '—' }}</span><form method="POST" action="{{ $url('modules.licenses.admin.escalation-groups.members.destroy',[$group->getRouteKey(),$member->getRouteKey()]) }}" onsubmit="return confirm(@js(__('licenses.delete_confirm')))" >@csrf @method('DELETE')<button class="lic-btn lic-btn--sm lic-btn--danger" type="submit"><i class="bi bi-trash"></i>{{ __('licenses.admin.member_remove') }}</button></form></article>@empty<div class="lic-empty">{{ __('licenses.admin.empty') }}</div>@endforelse</section></div>
<aside class="lic-panel"><h2 class="lic-panel__title"><i class="bi bi-person-plus"></i>{{ __('licenses.admin.add_member') }}</h2><form method="POST" action="{{ $url('modules.licenses.admin.escalation-groups.members.store',$group->getRouteKey()) }}">@csrf<div class="lic-field"><label for="member_user_id">{{ __('licenses.fields.responsible') }} <span class="lic-required">*</span></label><select id="member_user_id" name="user_id" required class="form-select"><option value="">—</option>@foreach($usersList as $user)<option value="{{ $user->hr_id ?? $user->id }}" @selected((string)old('user_id')===(string)($user->hr_id ?? $user->id))>{{ $userName($user) }}</option>@endforeach</select></div><button class="lic-btn lic-btn--primary mt-2" type="submit">{{ __('licenses.admin.add_member') }}</button></form></aside></div>
</div>@endsection
