@extends('layouts.app')
@section('title','الموافقات الطبية للتنويم')
@section('content')
<div class="container-fluid py-3" dir="rtl">
    <div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><h1 class="h4">الموافقات الطبية</h1><p class="text-muted">الفرع المخصص للموافقات الطبية: 10.</p></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-secondary" href="{{ route('modules.admission-inpatient.doctors.index') }}">أطباء التنويم</a><a class="btn btn-outline-secondary" href="{{ route('modules.admission-inpatient.reference.index','medical-approval-statuses') }}">حالات الموافقة</a><a class="btn btn-outline-secondary" href="{{ route('modules.admission-inpatient.reference.index','medical-approval-rejection-reasons') }}">أسباب الرفض</a><a class="btn btn-outline-secondary" href="{{ route('modules.admission-inpatient.contacts.index','cc') }}">جهات الاتصال</a><a class="btn btn-primary" href="{{ route('modules.admission-inpatient.approvals.create') }}">إشعار جديد</a></div></div>
    <div class="row g-3 mb-3">@foreach([['الإجمالي','total',''],['موافق عليه','approved','text-success'],['غير موافق','not_approved','text-danger'],['محول للتحصيل','transferred','']] as [$label,$key,$class])<div class="col-md-3"><div class="card border-0 shadow-sm"><div class="card-body"><small>{{ $label }}</small><h2 class="h4 mb-0 {{ $class }}">{{ $stats[$key] }}</h2></div></div></div>@endforeach</div>
    <form class="card border-0 shadow-sm mb-3"><div class="card-body row g-2"><div class="col-md-4"><input class="form-control" name="search" value="{{ $filters['search'] }}" placeholder="المريض، الهوية، الغرفة"></div><div class="col-md-2"><select class="form-select" name="status"><option value="">كل الحالات</option>@foreach($options['statuses'] as $status)<option value="{{ $status->id }}" @selected((int)$filters['status'] === (int)$status->id)>{{ $status->name_ar ?: $status->name_en }}</option>@endforeach</select></div><div class="col-md-2"><input type="date" class="form-control" name="from" value="{{ $filters['from'] }}"></div><div class="col-md-2"><input type="date" class="form-control" name="to" value="{{ $filters['to'] }}"></div><div class="col-md-1"><select class="form-select" name="sent"><option value="">الكل</option><option value="1" @selected($filters['sent'] === '1')>محول</option><option value="0" @selected($filters['sent'] === '0')>غير محول</option></select></div><div class="col-md-1"><button class="btn btn-outline-primary w-100">بحث</button></div></div></form>
    <div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>#</th><th>المريض</th><th>الهوية</th><th>الغرفة</th><th>الحالة الحالية</th><th>التحصيل</th><th>التاريخ</th><th></th></tr></thead><tbody>@forelse($notifications as $row)@php($latest=$row->logs->first())<tr><td>{{ $row->id }}</td><td>{{ $row->patient_name }}</td><td>{{ $row->patient_identity }}</td><td>{{ $row->room_number }}</td><td>{{ $latest->status_name ?? '—' }}</td><td>{{ (int)($row->sent_to_collection ?? 0) ? 'تم':'لم يتم' }}</td><td>{{ $row->created_at }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('modules.admission-inpatient.approvals.show',$row->id) }}">عرض</a></td></tr>@empty<tr><td colspan="8" class="text-center py-5 text-muted">لا توجد إشعارات.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $notifications->links() }}</div></div>
</div>
@endsection
